@extends('layouts.contentNavbarLayout')
@section('title', 'Detail Pegawai')
@section('content')
@php($money = fn ($value) => 'Rp '.number_format((float) $value, 0, ',', '.'))
@php($activeTab = request('tab', 'profile'))
<div class="container-fluid">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4">
    <div><h4 class="mb-1">{{ $employee->name }}</h4><p class="text-muted mb-0">{{ $employee->employee_no }} · {{ $employee->company?->name }} · {{ $employee->branch?->name ?: 'Kantor Pusat' }}</p></div>
    <div class="d-flex gap-2"><a href="{{ route('employees.edit', $employee) }}" class="btn btn-warning"><i class="ti ti-edit me-1"></i>Edit Pegawai</a><a href="{{ route('employees.index') }}" class="btn btn-label-secondary">Kembali</a></div>
  </div>

  <div class="card mb-4"><div class="card-body"><div class="row g-3 align-items-center"><div class="col-auto"><img src="{{ $employee->photo_url }}" class="rounded-circle" width="76" height="76" alt="Foto pegawai"></div><div class="col"><div class="d-flex flex-wrap gap-2 mb-1"><span class="badge bg-label-{{ $employee->status_badge }}">{{ $employee->status_label }}</span><span class="badge bg-label-{{ $employee->employment_badge }}">{{ $employee->employment_label }}</span></div><div class="fw-semibold">{{ $employee->position?->name ?: 'Jabatan belum diset' }}</div><small class="text-muted">{{ $employee->division?->name ?: 'Divisi belum diset' }} · Supervisor: {{ $employee->supervisor?->name ?: '-' }}</small></div><div class="col-sm-auto text-sm-end"><small class="text-muted d-block">Penghasilan dasar saat ini</small><strong>{{ $money($employee->total_income) }}</strong></div></div></div></div>

  <div class="card"><div class="card-header border-bottom"><ul class="nav nav-tabs card-header-tabs" role="tablist"><li class="nav-item"><button class="nav-link {{ $activeTab === 'profile' ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#profile" type="button">Profil</button></li><li class="nav-item"><a class="nav-link" href="{{ route('employees.documents.index', $employee) }}">Dokumen</a></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#employment" type="button">Status Kerja</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#contract" type="button">Kontrak <span class="badge bg-label-secondary">{{ $contracts->count() }}</span></button></li><li class="nav-item"><button class="nav-link {{ $activeTab === 'attendance' ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#attendance" type="button">Absensi <span class="badge bg-label-secondary">{{ $attendances->count() }}</span></button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#kpi" type="button">KPI <span class="badge bg-label-secondary">{{ $kpiAssessments->count() }}</span></button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#payroll" type="button">Payroll <span class="badge bg-label-secondary">{{ $payrollSlips->count() }}</span></button></li>@if($canViewRequests)<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#requests" type="button">Pengajuan <span class="badge bg-label-secondary">{{ $employeeRequests->count() }}</span></button></li>@endif
@if($canViewTasks)<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#tasks" type="button">Tugas <span class="badge bg-label-secondary">{{ $employeeTasks->count() }}</span></button></li>@endif</ul></div>
    <div class="card-body"><div class="tab-content">
      <div class="tab-pane fade {{ $activeTab === 'profile' ? 'show active' : '' }}" id="profile"><div class="row"><div class="col-lg-6"><table class="table table-borderless mb-0"><tr><th width="180">Email</th><td>{{ $employee->email ?: '-' }}</td></tr><tr><th>Telepon / WA</th><td>{{ $employee->contact }}</td></tr><tr><th>Tanggal lahir</th><td>{{ $employee->birth_date?->format('d/m/Y') ?: '-' }}</td></tr><tr><th>Alamat</th><td>{{ $employee->full_address ?: '-' }}</td></tr></table></div><div class="col-lg-6"><table class="table table-borderless mb-0"><tr><th width="180">Company</th><td>{{ $employee->company?->name }}</td></tr><tr><th>Branch / Site</th><td>{{ $employee->branch?->parent?->name ? $employee->branch->parent->name.' / '.$employee->branch->name : ($employee->branch?->name ?: '-') }}</td></tr><tr><th>Divisi</th><td>{{ $employee->division?->name ?: '-' }}</td></tr><tr><th>Jabatan</th><td>{{ $employee->position?->name ?: '-' }}</td></tr></table></div></div></div>
      <div class="tab-pane fade" id="employment"><div class="row"><div class="col-lg-6"><table class="table table-borderless"><tr><th width="210">Tanggal masuk</th><td>{{ $employee->join_date?->format('d/m/Y') ?: '-' }}</td></tr><tr><th>Masa probation</th><td>{{ $employee->probation_end_date?->format('d/m/Y') ?: '-' }}</td></tr><tr><th>Atasan</th><td>{{ $employee->manager?->name ?: '-' }}</td></tr></table></div><div class="col-lg-6"><table class="table table-borderless"><tr><th width="210">Login OEMS</th><td>{{ $employee->user?->email ?: 'Belum dibuat' }}</td></tr><tr><th>Terakhir login</th><td>{{ $employee->user?->last_login_at?->format('d/m/Y H:i') ?: '-' }}</td></tr><tr><th>Wajib presensi</th><td>{{ $employee->is_attendance_required ? 'Ya' : 'Tidak' }}</td></tr>
            @can('employees.update')
              <tr>
                <th>Akun OvallHR</th>
                <td>
                  <div>{{ $employee->user?->email ?: 'Belum dibuat' }}</div>
                  <form method="POST" action="{{ route('employees.mobile-account.reset', $employee) }}" class="mt-2" onsubmit="return confirm('Siapkan atau reset akun OvallHR? Password sementara menjadi 12345678 dan pegawai wajib menggantinya setelah login.');">
                    @csrf
                    <button type="submit" class="btn btn-sm btn-label-warning" {{ $employee->email ? '' : 'disabled' }}>
                      <i class="ti ti-key me-1"></i>{{ $employee->user ? 'Reset Password OvallHR' : 'Buat Akun OvallHR' }}
                    </button>
                  </form>
                  <small class="text-muted d-block mt-1">Default: 12345678 &middot; wajib ganti setelah login.</small>
                </td>
              </tr>
            @endcan</table></div></div></div>
      <div class="tab-pane fade" id="contract"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">Riwayat Kontrak</h6><small class="text-muted">Detail dan dokumen PDF tersedia dari setiap kontrak.</small></div><a class="btn btn-sm btn-primary" href="{{ route('hr.contracts.create') }}"><i class="ti ti-plus me-1"></i>Buat Kontrak</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>No. Kontrak</th><th>Jenis</th><th>Periode</th><th>Status</th><th></th></tr></thead><tbody>@forelse($contracts as $contract)<tr><td>{{ $contract->contract_no }}</td><td>{{ $contract->contractType?->name ?: '-' }}</td><td>{{ $contract->start_date?->format('d/m/Y') }} – {{ $contract->end_date?->format('d/m/Y') ?: 'Berlaku' }}</td><td><span class="badge bg-label-{{ $contract->status_badge }}">{{ $contract->status_label }}</span></td><td><a class="btn btn-sm btn-label-primary" href="{{ route('hr.contracts.show', $contract) }}">Detail</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada kontrak untuk pegawai ini.</td></tr>@endforelse</tbody></table></div></div>
      <div class="tab-pane fade {{ $activeTab === 'attendance' ? 'show active' : '' }}" id="attendance">
  <div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h6 class="mb-1">Riwayat Kehadiran Pegawai</h6><small class="text-muted">31 presensi terakhir, catatan, GPS, selfie, dan status approval HR.</small></div><a class="btn btn-sm btn-primary" href="{{ route('attendance.index', ['branch_id' => $employee->branch_id]) }}">Monitoring Absensi</a></div>
  <div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Tanggal</th><th>Shift</th><th>Masuk / Pulang</th><th>Catatan</th><th>GPS & Bukti</th><th>Status</th></tr></thead><tbody>@forelse($attendances as $attendance)
    @php($approval = $attendance->approval_status ?: 'approved')
    <tr><td>{{ $attendance->date?->format('d/m/Y') }}</td><td>{{ $attendance->shift?->name ?: 'Tanpa shift' }}</td><td><strong>{{ $attendance->clock_in_at?->timezone($employee->company?->timezone ?: 'Asia/Jakarta')->format('H:i') ?: '-' }}</strong><div class="small text-muted">Pulang: {{ $attendance->clock_out_at?->timezone($employee->company?->timezone ?: 'Asia/Jakarta')->format('H:i') ?: '-' }}</div></td><td><div class="small">{{ $attendance->notes ?: '-' }}</div>@if($attendance->rejection_reason)<div class="small text-danger mt-1">Ditolak: {{ $attendance->rejection_reason }}</div>@endif</td><td><div class="small {{ $attendance->geofence_validated ? 'text-success' : 'text-warning' }}">{{ $attendance->geofence_validated ? 'GPS tervalidasi' : 'GPS perlu review' }}</div><div class="d-flex gap-1 mt-1">@if($attendance->in_photo)<a class="btn btn-xs btn-label-primary" target="_blank" href="{{ route('attendance.records.proof', [$attendance, 'in']) }}">Selfie masuk</a>@endif @if($attendance->out_photo)<a class="btn btn-xs btn-label-primary" target="_blank" href="{{ route('attendance.records.proof', [$attendance, 'out']) }}">Selfie pulang</a>@endif</div></td><td><span class="badge bg-label-secondary">{{ str($attendance->status ?: 'hadir')->replace('_', ' ')->title() }}</span><div class="mt-1"><span class="badge bg-label-{{ $approval === 'approved' ? 'success' : ($approval === 'rejected' ? 'danger' : 'warning') }}">{{ str($approval)->title() }}</span></div></td></tr>
  @empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada presensi.</td></tr>@endforelse</tbody></table></div>
</div><div class="tab-pane fade" id="kpi"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">Penilaian KPI</h6><small class="text-muted">Nilai per periode dan bonus KPI pegawai.</small></div><a class="btn btn-sm btn-primary" href="{{ route('hr.kpi.assessments.create') }}">Input KPI</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Periode</th><th>Nilai</th><th>Bonus</th><th>Status</th><th></th></tr></thead><tbody>@forelse($kpiAssessments as $assessment)<tr><td>{{ sprintf('%02d/%04d', $assessment->period_month, $assessment->period_year) }}</td><td>{{ number_format((float) $assessment->total_score, 2, ',', '.') }}</td><td>{{ $money($assessment->bonus_amount) }}</td><td>{{ str($assessment->status)->replace('_',' ')->title() }}</td><td><a class="btn btn-sm btn-label-primary" href="{{ route('hr.kpi.assessments.show', $assessment) }}">Detail</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada penilaian KPI.</td></tr>@endforelse</tbody></table></div></div>
      <div class="tab-pane fade" id="payroll"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">Slip Payroll</h6><small class="text-muted">Hanya payroll yang sudah diproses dalam company aktif.</small></div><a class="btn btn-sm btn-primary" href="{{ route('hr.payroll.index') }}">Buka Payroll</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Periode</th><th>No. Slip</th><th>Penghasilan</th><th>Potongan</th><th>THP</th><th></th></tr></thead><tbody>@forelse($payrollSlips as $slip)<tr><td>{{ $slip->period ? sprintf('%02d/%04d', $slip->period->period_month, $slip->period->period_year) : '-' }}</td><td>{{ $slip->slip_no }}</td><td>{{ $money($slip->gross_income) }}</td><td>{{ $money($slip->total_deduction) }}</td><td>{{ $money($slip->net_pay) }}</td><td><a class="btn btn-sm btn-label-primary" href="{{ route('hr.payroll.payslip', $slip) }}" target="_blank">Cetak</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada slip payroll.</td></tr>@endforelse</tbody></table></div></div>
      @if($canViewRequests)<div class="tab-pane fade" id="requests"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">Riwayat Pengajuan</h6><small class="text-muted">Cuti, izin, sakit, lembur, kasbon, dan piutang dari company aktif.</small></div><a class="btn btn-sm btn-primary" href="{{ route('hr.requests.index') }}">Buka Approval</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Jenis</th><th>Diajukan</th><th>Periode</th><th>Nominal</th><th>Status</th></tr></thead><tbody>@forelse($employeeRequests as $item)<tr><td>{{ str($item->type)->replace('_',' ')->title() }}</td><td>{{ $item->submitted_at?->format('d/m/Y H:i') ?: '-' }}</td><td>{{ $item->start_date?->format('d/m/Y') ?: '-' }}{{ $item->end_date ? ' - '.$item->end_date->format('d/m/Y') : '' }}</td><td>{{ $item->requested_amount !== null ? $money($item->requested_amount) : '-' }}</td><td><span class="badge bg-label-secondary">{{ str($item->status)->replace('_',' ')->title() }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada pengajuan.</td></tr>@endforelse</tbody></table></div></div>@endif
      @if($canViewTasks)<div class="tab-pane fade" id="tasks"><div class="mb-3"><h6 class="mb-1">Tugas Pegawai</h6><small class="text-muted">Ringkasan tugas operasional OvallHR pada company aktif.</small></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Tugas</th><th>Prioritas</th><th>Target</th><th>Status</th></tr></thead><tbody>@forelse($employeeTasks as $task)<tr><td><div class="fw-semibold">{{ $task->title }}</div><small class="text-muted">{{ str($task->description ?: 'Tanpa keterangan')->limit(100) }}</small></td><td>{{ str($task->priority)->replace('_',' ')->title() }}</td><td>{{ $task->due_at?->format('d/m/Y H:i') ?: '-' }}</td><td><span class="badge bg-label-secondary">{{ str($task->status)->replace('_',' ')->title() }}</span></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Belum ada tugas.</td></tr>@endforelse</tbody></table></div></div>@endif    </div></div></div>
</div>
@endsection
