@extends('layouts.contentNavbarLayout')
@section('title', 'Detail Pegawai')
@section('content')
@php($money = fn ($value) => 'Rp '.number_format((float) $value, 0, ',', '.'))
<div class="container-fluid">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4">
    <div><h4 class="mb-1">{{ $employee->name }}</h4><p class="text-muted mb-0">{{ $employee->employee_no }} · {{ $employee->company?->name }} · {{ $employee->branch?->name ?: 'Kantor Pusat' }}</p></div>
    <div class="d-flex gap-2"><a href="{{ route('employees.edit', $employee) }}" class="btn btn-warning"><i class="ti ti-edit me-1"></i>Edit Pegawai</a><a href="{{ route('employees.index') }}" class="btn btn-label-secondary">Kembali</a></div>
  </div>

  <div class="card mb-4"><div class="card-body"><div class="row g-3 align-items-center"><div class="col-auto"><img src="{{ $employee->photo_url }}" class="rounded-circle" width="76" height="76" alt="Foto pegawai"></div><div class="col"><div class="d-flex flex-wrap gap-2 mb-1"><span class="badge bg-label-{{ $employee->status_badge }}">{{ $employee->status_label }}</span><span class="badge bg-label-{{ $employee->employment_badge }}">{{ $employee->employment_label }}</span></div><div class="fw-semibold">{{ $employee->position?->name ?: 'Jabatan belum diset' }}</div><small class="text-muted">{{ $employee->division?->name ?: 'Divisi belum diset' }} · Supervisor: {{ $employee->supervisor?->name ?: '-' }}</small></div><div class="col-sm-auto text-sm-end"><small class="text-muted d-block">Penghasilan dasar saat ini</small><strong>{{ $money($employee->total_income) }}</strong></div></div></div></div>

  <div class="card"><div class="card-header border-bottom"><ul class="nav nav-tabs card-header-tabs" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile" type="button">Profil</button></li><li class="nav-item"><a class="nav-link" href="{{ route('employees.documents.index', $employee) }}">Dokumen</a></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#employment" type="button">Status Kerja</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#contract" type="button">Kontrak <span class="badge bg-label-secondary">{{ $contracts->count() }}</span></button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#attendance" type="button">Absensi <span class="badge bg-label-secondary">{{ $attendances->count() }}</span></button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#kpi" type="button">KPI <span class="badge bg-label-secondary">{{ $kpiAssessments->count() }}</span></button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#payroll" type="button">Payroll <span class="badge bg-label-secondary">{{ $payrollSlips->count() }}</span></button></li></ul></div>
    <div class="card-body"><div class="tab-content">
      <div class="tab-pane fade show active" id="profile"><div class="row"><div class="col-lg-6"><table class="table table-borderless mb-0"><tr><th width="180">Email</th><td>{{ $employee->email ?: '-' }}</td></tr><tr><th>Telepon / WA</th><td>{{ $employee->contact }}</td></tr><tr><th>Tanggal lahir</th><td>{{ $employee->birth_date?->format('d/m/Y') ?: '-' }}</td></tr><tr><th>Alamat</th><td>{{ $employee->full_address ?: '-' }}</td></tr></table></div><div class="col-lg-6"><table class="table table-borderless mb-0"><tr><th width="180">Company</th><td>{{ $employee->company?->name }}</td></tr><tr><th>Branch / Site</th><td>{{ $employee->branch?->parent?->name ? $employee->branch->parent->name.' / '.$employee->branch->name : ($employee->branch?->name ?: '-') }}</td></tr><tr><th>Divisi</th><td>{{ $employee->division?->name ?: '-' }}</td></tr><tr><th>Jabatan</th><td>{{ $employee->position?->name ?: '-' }}</td></tr></table></div></div></div>
      <div class="tab-pane fade" id="employment"><div class="row"><div class="col-lg-6"><table class="table table-borderless"><tr><th width="210">Tanggal masuk</th><td>{{ $employee->join_date?->format('d/m/Y') ?: '-' }}</td></tr><tr><th>Masa probation</th><td>{{ $employee->probation_end_date?->format('d/m/Y') ?: '-' }}</td></tr><tr><th>Atasan</th><td>{{ $employee->manager?->name ?: '-' }}</td></tr></table></div><div class="col-lg-6"><table class="table table-borderless"><tr><th width="210">Login OEMS</th><td>{{ $employee->user?->email ?: 'Belum dibuat' }}</td></tr><tr><th>Terakhir login</th><td>{{ $employee->user?->last_login_at?->format('d/m/Y H:i') ?: '-' }}</td></tr><tr><th>Wajib presensi</th><td>{{ $employee->is_attendance_required ? 'Ya' : 'Tidak' }}</td></tr></table></div></div></div>
      <div class="tab-pane fade" id="contract"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">Riwayat Kontrak</h6><small class="text-muted">Detail dan dokumen PDF tersedia dari setiap kontrak.</small></div><a class="btn btn-sm btn-primary" href="{{ route('hr.contracts.create') }}"><i class="ti ti-plus me-1"></i>Buat Kontrak</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>No. Kontrak</th><th>Jenis</th><th>Periode</th><th>Status</th><th></th></tr></thead><tbody>@forelse($contracts as $contract)<tr><td>{{ $contract->contract_no }}</td><td>{{ $contract->contractType?->name ?: '-' }}</td><td>{{ $contract->start_date?->format('d/m/Y') }} – {{ $contract->end_date?->format('d/m/Y') ?: 'Berlaku' }}</td><td><span class="badge bg-label-{{ $contract->status_badge }}">{{ $contract->status_label }}</span></td><td><a class="btn btn-sm btn-label-primary" href="{{ route('hr.contracts.show', $contract) }}">Detail</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada kontrak untuk pegawai ini.</td></tr>@endforelse</tbody></table></div></div>
      <div class="tab-pane fade" id="attendance"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">31 Presensi Terakhir</h6><small class="text-muted">Bukti selfie dan detail lengkap dapat dibuka dari modul Absensi.</small></div><a class="btn btn-sm btn-primary" href="{{ route('attendance.index') }}">Buka Absensi</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Tanggal</th><th>Masuk</th><th>Pulang</th><th>Shift</th><th>Status</th></tr></thead><tbody>@forelse($attendances as $attendance)<tr><td>{{ $attendance->date?->format('d/m/Y') }}</td><td>{{ $attendance->clock_in_at?->timezone($employee->company?->timezone ?: 'Asia/Jakarta')->format('H:i') ?: '-' }}</td><td>{{ $attendance->clock_out_at?->timezone($employee->company?->timezone ?: 'Asia/Jakarta')->format('H:i') ?: '-' }}</td><td>{{ $attendance->shift?->name ?: '-' }}</td><td><span class="badge bg-label-secondary">{{ str($attendance->status ?: 'hadir')->replace('_', ' ')->title() }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada presensi.</td></tr>@endforelse</tbody></table></div></div>
      <div class="tab-pane fade" id="kpi"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">Penilaian KPI</h6><small class="text-muted">Nilai per periode dan bonus KPI pegawai.</small></div><a class="btn btn-sm btn-primary" href="{{ route('hr.kpi.assessments.create') }}">Input KPI</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Periode</th><th>Nilai</th><th>Bonus</th><th>Status</th><th></th></tr></thead><tbody>@forelse($kpiAssessments as $assessment)<tr><td>{{ sprintf('%02d/%04d', $assessment->period_month, $assessment->period_year) }}</td><td>{{ number_format((float) $assessment->total_score, 2, ',', '.') }}</td><td>{{ $money($assessment->bonus_amount) }}</td><td>{{ str($assessment->status)->replace('_',' ')->title() }}</td><td><a class="btn btn-sm btn-label-primary" href="{{ route('hr.kpi.assessments.show', $assessment) }}">Detail</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada penilaian KPI.</td></tr>@endforelse</tbody></table></div></div>
      <div class="tab-pane fade" id="payroll"><div class="d-flex justify-content-between mb-3"><div><h6 class="mb-1">Slip Payroll</h6><small class="text-muted">Hanya payroll yang sudah diproses dalam company aktif.</small></div><a class="btn btn-sm btn-primary" href="{{ route('hr.payroll.index') }}">Buka Payroll</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Periode</th><th>No. Slip</th><th>Penghasilan</th><th>Potongan</th><th>THP</th><th></th></tr></thead><tbody>@forelse($payrollSlips as $slip)<tr><td>{{ $slip->period ? sprintf('%02d/%04d', $slip->period->period_month, $slip->period->period_year) : '-' }}</td><td>{{ $slip->slip_no }}</td><td>{{ $money($slip->gross_income) }}</td><td>{{ $money($slip->total_deduction) }}</td><td>{{ $money($slip->net_pay) }}</td><td><a class="btn btn-sm btn-label-primary" href="{{ route('hr.payroll.payslip', $slip) }}" target="_blank">Cetak</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada slip payroll.</td></tr>@endforelse</tbody></table></div></div>
    </div></div></div>
</div>
@endsection
