@php($editing = isset($branch))
<div class="row g-3">
  <div class="col-md-6"><label class="form-label">Company induk</label><input class="form-control" readonly value="{{ $company->legal_name ?: $company->name }}"></div>
  <div class="col-md-3"><label class="form-label">Kode otomatis</label><input class="form-control" readonly value="{{ $editing ? $branch->code : 'Dibuat saat disimpan' }}"></div>
  <div class="col-md-3"><label class="form-label">Tipe <span class="text-danger">*</span></label><select class="form-select @error('type') is-invalid @enderror" name="type" id="branchType" required>@foreach(['head_office'=>'Head Office','branch'=>'Branch','site'=>'Site','warehouse'=>'Gudang','project'=>'Project'] as $value=>$label)<option value="{{ $value }}" @selected(old('type',$branch->type ?? 'branch')===$value)>{{ $label }}</option>@endforeach</select>@error('type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label">Nama Branch / Site <span class="text-danger">*</span></label><input class="form-control @error('name') is-invalid @enderror" name="name" required value="{{ old('name',$branch->name ?? '') }}">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6" id="parentField"><label class="form-label">Branch induk <span class="text-danger" id="siteRequired">*</span></label><select class="form-select @error('parent_branch_id') is-invalid @enderror" name="parent_branch_id"><option value="">-- Tidak ada / pilih Branch --</option>@foreach($parents as $parent)<option value="{{ $parent->id }}" @selected((string)old('parent_branch_id',$branch->parent_branch_id ?? '')===(string)$parent->id)>{{ $parent->name }} ({{ $parent->code }})</option>@endforeach</select><div class="form-text">Wajib untuk tipe Site. Branch dan Head Office berdiri langsung di bawah PT OSM.</div>@error('parent_branch_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
  <div class="col-md-6"><label class="form-label">PIC operasional</label><input class="form-control" name="pic_name" value="{{ old('pic_name',$branch->pic_name ?? '') }}" placeholder="Nama penanggung jawab unit"></div>
  <div class="col-md-6"><label class="form-label">Telepon PIC</label><input class="form-control" name="pic_phone" value="{{ old('pic_phone',$branch->pic_phone ?? '') }}"></div>
  <div class="col-md-6"><label class="form-label">Email unit</label><input type="email" class="form-control" name="email" value="{{ old('email',$branch->email ?? '') }}"></div>
  <div class="col-md-6"><label class="form-label">Telepon unit</label><input class="form-control" name="phone" value="{{ old('phone',$branch->phone ?? '') }}"></div>
  <div class="col-12"><label class="form-label">Alamat</label><textarea class="form-control" name="address" rows="3">{{ old('address',$branch->address ?? '') }}</textarea></div>
  <div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status">@foreach(['active'=>'Aktif','inactive'=>'Nonaktif','closed'=>'Tutup'] as $value=>$label)<option value="{{ $value }}" @selected(old('status',$branch->status ?? 'active')===$value)>{{ $label }}</option>@endforeach</select></div>
</div>
<script>const type=document.getElementById('branchType'), parent=document.getElementById('parentField'), req=document.getElementById('siteRequired');function syncParent(){const site=type.value==='site';parent.classList.toggle('d-none',!site);req.classList.toggle('d-none',!site)}type.addEventListener('change',syncParent);syncParent();</script>
