<!doctype html>
<html lang="id"><head><meta charset="utf-8"><title>{{ $companyDocument->name }}</title><style>
@page{size:A4;margin:16mm 17mm}body{font-family:Arial,sans-serif;color:#111827;font-size:11pt;line-height:1.5}.paper{position:relative}.letterhead{display:grid;grid-template-columns:160px auto;column-gap:20px;align-items:center;padding-bottom:12px}.letterhead-logo{text-align:center}.letterhead-logo img{width:180px;max-height:88px;object-fit:contain}.letterhead-company{text-align:center}.letterhead-company h1{font-size:18pt;font-weight:700;margin:0 0 4px}.letterhead-company p{font-size:10pt;margin:2px}.letterhead-border{margin-top:10px;border-top:3px solid #000;border-bottom:1px solid #000;height:4px;margin-bottom:28px}.title{text-align:center;margin:22px 0}.title h2{margin:0 0 5px;font-size:14pt}.content table{border-collapse:collapse;width:100%;margin:10px 0}.content td,.content th{padding:6px;vertical-align:top}.content h2{font-size:12pt;margin-top:20px}.content p{margin:8px 0}.sign{display:flex;justify-content:space-between;text-align:center;margin-top:60px}.sign div{width:38%}.footer{position:fixed;bottom:-6mm;left:0;right:0;border-top:1px solid #d1d5db;padding-top:5px;font-size:8pt;color:#64748b}@media print{.no-print{display:none}}</style></head><body>
<div class="no-print" style="margin-bottom:15px"><button onclick="window.print()">Cetak / Simpan PDF</button></div>
<div class="paper"><div class="letterhead"><div class="letterhead-logo"><img src="{{ asset('assets/img/logo_osm_transparent.png') }}" alt="Logo OSM"></div><div class="letterhead-company"><h1>{{ strtoupper($company->legal_name ?: $company->name) }}</h1><p>{{ $company->address ?: 'Perum Alam Tirta Lestari Blok D No.005' }}</p><p>{{ $company->phone ?: '(0251) 2027233' }} | {{ $company->email ?: 'office@osm.net.id' }} | www.osm.net.id</p></div></div><div class="letterhead-border"></div>
<div class="title"><h2>{{ strtoupper($values['subject'] ?? $companyDocument->subject ?? $companyDocument->name) }}</h2>@if(!empty($values['document_no']))<div>Nomor: {{ $values['document_no'] }}</div>@endif</div>
<div class="content">{!! $renderedBody !!}</div>
<div class="sign"><div>Mengetahui,<br><br><br><br><strong>________________________</strong><br>{{ $company->legal_name ?: $company->name }}</div><div>{{ $values['document_date'] ?? now()->translatedFormat('d F Y') }}<br><br><br><br><strong>________________________</strong><br>Pihak Terkait</div></div>
</div><div class="footer">Dokumen dibuat dari AppOEMS · Master {{ $companyDocument->code }} v{{ $companyDocument->template_version }}</div></body></html>
