<!doctype html><html lang="id"><head><meta charset="utf-8"><title>{{ $companyDocument->name }}</title><style>
@page{size:A4;margin:18mm 17mm}body{font-family:Arial,sans-serif;color:#18212f;font-size:11pt;line-height:1.5}.head{display:flex;gap:14px;align-items:center;border-bottom:3px solid #0f5c96;padding-bottom:10px;margin-bottom:20px}.head img{width:92px;max-height:58px;object-fit:contain}.head h1{font-size:16pt;margin:0;color:#0f2747}.head p{margin:2px 0;color:#4b5563;font-size:9pt}.title{text-align:center;margin:22px 0}.title h2{margin:0 0 5px;font-size:14pt}.content table{border-collapse:collapse;width:100%;margin:10px 0}.content td,.content th{padding:6px;vertical-align:top}.content h2{font-size:12pt;margin-top:20px;color:#0f2747}.content p{margin:8px 0}.sign{display:flex;justify-content:space-between;text-align:center;margin-top:60px}.sign div{width:38%}.footer{position:fixed;bottom:-6mm;left:0;right:0;border-top:1px solid #d1d5db;padding-top:5px;font-size:8pt;color:#64748b}@media print{.no-print{display:none}}</style></head><body>
<div class="no-print" style="margin-bottom:15px"><button onclick="window.print()">Cetak / Simpan PDF</button></div>
<div class="head"><img src="{{ asset('assets/img/logo_osm_transparent.png') }}" alt="OSM"><div><h1>{{ $company->legal_name ?: $company->name }}</h1><p>{{ $company->address }}<br>{{ $company->phone }} · {{ $company->email }}</p></div></div>
<div class="title"><h2>{{ strtoupper($values['subject'] ?? $companyDocument->subject ?? $companyDocument->name) }}</h2>@if(!empty($values['document_no']))<div>Nomor: {{ $values['document_no'] }}</div>@endif</div>
<div class="content">{!! $renderedBody !!}</div>
<div class="sign"><div>Mengetahui,<br><br><br><br><strong>________________________</strong><br>PT Ovall Solusindo Mandiri</div><div>{{ $values['document_date'] ?? now()->translatedFormat('d F Y') }}<br><br><br><br><strong>________________________</strong><br>Pihak Terkait</div></div>
<div class="footer">Dokumen dibuat dari AppOEMS · Master {{ $companyDocument->code }} v{{ $companyDocument->template_version }}</div>
</body></html>
