@extends('layouts.contentNavbarLayout')

@section('title', 'Detail KPI Pegawai')

@section('content')
<div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><h4 class="mb-1">Detail KPI {{ $assessment->employee?->name }}</h4><p class="text-muted mb-0">Periode {{ sprintf('%02d', $assessment->period_month) }}/{{ $assessment->period_year }}</p></div><a href="{{ route('hr.kpi.index') }}" class="btn btn-label-secondary">Kembali</a></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    <div class="row mb-4"><div class="col-md-8"><div class="card h-100"><div class="card-body"><div class="row"><div class="col-md-6"><small class="text-muted">Pegawai</small><h5>{{ $assessment->employee?->name }}</h5><p class="mb-0">{{ $assessment->position?->name ?? '-' }}</p></div><div class="col-md-3"><small class="text-muted">Nilai / Grade</small><h3 class="mb-0">{{ number_format((float) $assessment->total_score, 2) }} <span class="badge bg-label-primary">{{ $assessment->grade }}</span></h3></div><div class="col-md-3"><small class="text-muted">Bonus KPI</small><h5 class="text-success">Rp {{ number_format((float) $assessment->bonus_amount, 0, ',', '.') }}</h5></div></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><small class="text-muted">Status</small><h5><span class="badge bg-label-{{ $assessment->status === 'approved' ? 'success' : ($assessment->status === 'rejected' ? 'danger' : 'warning') }}">{{ ucfirst($assessment->status) }}</span></h5><small>Penilai: {{ $assessment->assessor?->name ?? '-' }}</small><br><small>Approver: {{ $assessment->approver?->name ?? '-' }}</small></div></div></div></div>
    <div class="card mb-4"><div class="table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>Aspek</th><th>Pedoman</th><th>Bobot</th><th>Nilai</th><th>Hasil</th></tr></thead><tbody>@foreach($assessment->items as $item)<tr><td><strong>{{ $item->aspect_name }}</strong></td><td>{{ $item->guideline ?: '-' }}</td><td>{{ $item->weight }}%</td><td>{{ $item->score }}</td><td>{{ $item->weighted_score }}</td></tr>@endforeach</tbody></table></div></div>
    @if($assessment->notes)<div class="alert alert-info"><strong>Catatan penilai:</strong> {{ $assessment->notes }}</div>@endif
    @if($assessment->review_note)<div class="alert alert-{{ $assessment->status === 'rejected' ? 'danger' : 'success' }}"><strong>Catatan reviewer:</strong> {{ $assessment->review_note }}</div>@endif
    @if($assessment->status === 'submitted')<div class="card"><div class="card-body"><h5>Approval KPI</h5><div class="row"><div class="col-lg-6"><form method="POST" action="{{ route('hr.kpi.assessments.approve', $assessment) }}">@csrf<label class="form-label">Catatan approval (opsional)</label><textarea name="review_note" class="form-control mb-3" rows="3"></textarea><button class="btn btn-success"><i class="ti ti-circle-check"></i> Setujui KPI</button></form></div><div class="col-lg-6"><form method="POST" action="{{ route('hr.kpi.assessments.reject', $assessment) }}">@csrf<label class="form-label">Alasan pengembalian</label><textarea name="review_note" class="form-control mb-3" rows="3" required></textarea><button class="btn btn-danger"><i class="ti ti-circle-x"></i> Kembalikan KPI</button></form></div></div></div></div>@endif
</div>
@endsection
