@extends('layouts.contentNavbarLayout')
@section('title', 'Master Jabatan')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h4 class="mb-1">Master Jabatan</h4><p class="text-muted mb-0">Jabatan dan batas KPI terhubung ke PT OSM, Branch/Site, lalu Divisi agar payroll dan approval dapat ditelusuri.</p></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@can('position.create')<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Tambah Jabatan</h5></div><div class="card-body"><form method="POST" action="{{ route('master.positions.store') }}">@csrf @include('master.positions._form')<button class="btn btn-primary mt-3"><i class="ri ri-add-line me-1"></i>Simpan Jabatan</button></form></div></div>@endcan
<div class="card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Jabatan</th><th>Company / Branch-Site / Divisi</th><th>Default Kompensasi</th><th>Hak</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($positions as $position)
<tr><td><strong>{{ $position->name }}</strong><div class="small text-muted">{{ $position->code }} · {{ $position->grade ?: '-' }} · Level {{ $position->level }}</div></td><td><strong>PT OSM</strong><div class="small">{{ $position->branch?->parent?->name ? $position->branch->parent->name.' → ' : '' }}{{ $position->branch?->name ?: 'Lintas PT OSM' }}</div><div class="small text-muted">{{ $position->division?->name ?: 'Lintas divisi' }}</div></td><td>Gaji Rp {{ number_format((float)$position->default_basic_salary,0,',','.') }}<div class="small">KPI maks. Rp {{ number_format((float)$position->default_kpi_incentive_max,0,',','.') }}</div></td><td>@if($position->is_management)<span class="badge bg-label-info">Management</span>@endif @if($position->is_approver)<span class="badge bg-label-primary">Approver</span>@endif</td><td><span class="badge bg-label-{{ $position->status === 'active' ? 'success' : 'secondary' }}">{{ ucfirst($position->status) }}</span></td><td><div class="d-flex gap-1">@can('position.update')<button class="btn btn-sm btn-label-warning" data-bs-toggle="collapse" data-bs-target="#edit-position-{{ $position->id }}">Edit</button>@endcan @can('position.delete')<form method="POST" action="{{ route('master.positions.destroy',$position) }}" onsubmit="return confirm('Hapus jabatan ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-label-danger">Hapus</button></form>@endcan</div></td></tr>
@can('position.update')<tr class="collapse" id="edit-position-{{ $position->id }}"><td colspan="6" class="bg-lighter"><form method="POST" action="{{ route('master.positions.update',$position) }}">@csrf @method('PUT') @include('master.positions._form',['position'=>$position])<button class="btn btn-warning mt-3">Simpan Perubahan</button></form></td></tr>@endcan
@empty<tr><td colspan="6" class="text-center py-5 text-muted">Belum ada jabatan.</td></tr>@endforelse
</tbody></table></div>@if($positions->hasPages())<div class="card-body">{{ $positions->links() }}</div>@endif</div>
@endsection
