@extends('layouts.contentNavbarLayout')
@section('title', 'Pengaturan')
@section('content')
<div class="container-fluid"><div class="mb-4"><h4 class="mb-1">Pengaturan</h4><p class="text-muted mb-0">Pusat konfigurasi {{ $company->name }}. Setiap menu mengikuti company aktif dan permission pengguna.</p></div>
<div class="row g-4">
@can('company.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('settings.company-profile.index') }}"><div class="card-body"><i class="ri ri-building-line fs-2 text-primary"></i><h5 class="mt-3">Profil Perusahaan</h5><p class="text-muted mb-0">NPWP, NIB, akta, alamat, kontak, dan rekening PT OSM.</p></div></a></div>@endcan

@can('attendance.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('hr.settings.index') }}"><div class="card-body"><i class="ri ri-time-line fs-2 text-primary"></i><h5 class="mt-3">Kehadiran & Kebijakan HR</h5><p class="text-muted mb-0">GPS, selfie, retention, radius, tanggal gaji, dan kebijakan dasar.</p></div></a></div>@endcan
@can('payroll.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('hr.compensation.index') }}"><div class="card-body"><i class="ri ri-wallet-3-line fs-2 text-primary"></i><h5 class="mt-3">Payroll & Kompensasi</h5><p class="text-muted mb-0">Komponen gaji, tunjangan, dan kebijakan pembayaran.</p></div></a></div>@endcan
@can('bpjs-calculation.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('settings.bpjs-calculation.index') }}"><div class="card-body"><i class="ri ri-calculator-line fs-2 text-primary"></i><h5 class="mt-3">BPJS Calculation Engine</h5><p class="text-muted mb-0">Tarif, kepesertaan, beban perusahaan, dan simulasi.</p></div></a></div>@endcan
@can('bpjs-registration.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('hr.bpjs-readiness.index') }}"><div class="card-body"><i class="ri ri-shield-check-line fs-2 text-primary"></i><h5 class="mt-3">BPJS & Kepatuhan</h5><p class="text-muted mb-0">Kesiapan data perusahaan dan pekerja untuk proses resmi.</p></div></a></div>@endcan
@can('report.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('hr.reports.compliance.index') }}"><div class="card-body"><i class="ri ri-file-chart-line fs-2 text-primary"></i><h5 class="mt-3">Laporan Kepatuhan</h5><p class="text-muted mb-0">Ringkasan BPJS payroll dan kesiapan data Coretax.</p></div></a></div>@endcan
@can('users.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('settings.user-access.index') }}"><div class="card-body"><i class="ri ri-user-settings-line fs-2 text-primary"></i><h5 class="mt-3">Akun & Pengguna</h5><p class="text-muted mb-0">Akses akun, role, dan permission sistem.</p></div></a></div>@endcan
@can('integration.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('settings.integrations.index') }}"><div class="card-body"><i class="ri ri-plug-2-line fs-2 text-primary"></i><h5 class="mt-3">Integrasi</h5><p class="text-muted mb-0">Koneksi AppBill live, keamanan, audit, dan health check.</p></div></a></div>@endcan
@can('mobile-release.view')<div class="col-md-6 col-xl-4"><a class="card h-100 text-decoration-none" href="{{ route('settings.mobile-releases.index') }}"><div class="card-body"><i class="ri ri-smartphone-line fs-2 text-primary"></i><h5 class="mt-3">OvallHR APK</h5><p class="text-muted mb-0">Rilis, update wajib, riwayat versi, dan feature toggle.</p></div></a></div>@endcan
</div></div>
@endsection
