@extends('layouts.contentNavbarLayout')
@section('title', 'Profil Perusahaan')
@section('content')
@php($canUpdate = auth()->user()?->can('company.update'))
<div class="container-fluid">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h4 class="mb-1">Profil Perusahaan</h4><p class="text-muted mb-0">Identitas legal untuk PT OSM, dokumen, kontrak, BPJS, dan integrasi. Data selalu mengikuti company aktif.</p></div><a class="btn btn-outline-secondary" href="{{ route('settings.hub.index') }}"><i class="ri ri-arrow-left-line me-1"></i>Kembali</a></div>
  @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
  <form method="POST" action="{{ route('settings.company-profile.update') }}">@csrf @method('PUT')
    <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Identitas Perusahaan</h5></div><div class="card-body"><div class="row g-3">
      <div class="col-md-3"><label class="form-label">Kode Company</label><input class="form-control" value="{{ $company->code }}" disabled><small class="text-muted">Dikunci untuk konsistensi integrasi.</small></div>
      <div class="col-md-5"><label class="form-label">Nama Perusahaan</label><input name="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name',$company->name) }}" @disabled(! $canUpdate) required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
      <div class="col-md-4"><label class="form-label">Nama Legal</label><input name="legal_name" class="form-control" value="{{ old('legal_name',$company->legal_name) }}" @disabled(! $canUpdate)></div>
      <div class="col-md-4"><label class="form-label">Nama Brand</label><input name="brand_name" class="form-control" value="{{ old('brand_name',$company->brand_name) }}" @disabled(! $canUpdate)></div>
      <div class="col-md-4"><label class="form-label">Bentuk Usaha</label><input name="business_type" class="form-control" placeholder="Contoh: Perseroan Terbatas" value="{{ old('business_type',$company->business_type) }}" @disabled(! $canUpdate)></div>
      <div class="col-md-4"><label class="form-label">Bidang Usaha</label><input name="industry_type" class="form-control" placeholder="Contoh: Telekomunikasi / ISP" value="{{ old('industry_type',$company->industry_type) }}" @disabled(! $canUpdate)></div>
    </div></div></div>
    <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Legalitas</h5></div><div class="card-body"><div class="row g-3">
      <div class="col-md-4"><label class="form-label">NPWP</label><input name="npwp" class="form-control" value="{{ old('npwp',$company->npwp) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">NIB</label><input name="nib" class="form-control" value="{{ old('nib',$company->nib) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">SIUP</label><input name="siup" class="form-control" value="{{ old('siup',$company->siup) }}" @disabled(! $canUpdate)></div>
      <div class="col-md-4"><label class="form-label">TDP</label><input name="tdp" class="form-control" value="{{ old('tdp',$company->tdp) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">Nomor Akta</label><input name="akta_no" class="form-control" value="{{ old('akta_no',$company->akta_no) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">Tanggal Akta</label><input type="date" name="akta_date" class="form-control" value="{{ old('akta_date',$company->akta_date) }}" @disabled(! $canUpdate)></div>
    </div></div></div>
    <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Kontak & Alamat</h5></div><div class="card-body"><div class="row g-3">
      <div class="col-md-4"><label class="form-label">Email Perusahaan</label><input type="email" name="email" class="form-control" value="{{ old('email',$company->email) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">Telepon</label><input name="phone" class="form-control" value="{{ old('phone',$company->phone) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">WhatsApp / Ponsel</label><input name="mobile_phone" class="form-control" value="{{ old('mobile_phone',$company->mobile_phone) }}" @disabled(! $canUpdate)></div>
      <div class="col-md-6"><label class="form-label">Website</label><input name="website" class="form-control" value="{{ old('website',$company->website) }}" @disabled(! $canUpdate)></div><div class="col-md-6"><label class="form-label">Kode Pos</label><input name="postal_code" class="form-control" value="{{ old('postal_code',$company->postal_code) }}" @disabled(! $canUpdate)></div>
      <div class="col-12"><label class="form-label">Alamat</label><textarea name="address" rows="3" class="form-control" @disabled(! $canUpdate)>{{ old('address',$company->address) }}</textarea></div>
      <div class="col-md-3"><label class="form-label">Provinsi</label><input name="province" class="form-control" value="{{ old('province',$company->province) }}" @disabled(! $canUpdate)></div><div class="col-md-3"><label class="form-label">Kota / Kabupaten</label><input name="city" class="form-control" value="{{ old('city',$company->city) }}" @disabled(! $canUpdate)></div><div class="col-md-3"><label class="form-label">Kecamatan</label><input name="district" class="form-control" value="{{ old('district',$company->district) }}" @disabled(! $canUpdate)></div><div class="col-md-3"><label class="form-label">Kelurahan / Desa</label><input name="village" class="form-control" value="{{ old('village',$company->village) }}" @disabled(! $canUpdate)></div>
    </div></div></div>
    <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Rekening Perusahaan</h5><small class="text-muted">Isi hanya rekening resmi perusahaan untuk kebutuhan dokumen dan payroll.</small></div><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Nama Bank</label><input name="bank_name" class="form-control" value="{{ old('bank_name',$company->bank_name) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">Nomor Rekening</label><input name="bank_account_no" class="form-control" value="{{ old('bank_account_no',$company->bank_account_no) }}" @disabled(! $canUpdate)></div><div class="col-md-4"><label class="form-label">Atas Nama</label><input name="bank_account_name" class="form-control" value="{{ old('bank_account_name',$company->bank_account_name) }}" @disabled(! $canUpdate)></div></div></div></div>
    <div class="card"><div class="card-body"><label class="form-label">Catatan Internal</label><textarea name="notes" rows="3" class="form-control" @disabled(! $canUpdate)>{{ old('notes',$company->notes) }}</textarea>@if($canUpdate)<div class="text-end mt-3"><button class="btn btn-primary"><i class="ri ri-save-line me-1"></i>Simpan Profil Perusahaan</button></div>@else<div class="alert alert-info mt-3 mb-0">Akun ini hanya memiliki akses lihat. Edit hanya tersedia untuk Owner/Developer yang memiliki permission company.update.</div>@endif</div></div>
  </form>
</div>
@endsection