<?php $__env->startSection('title', 'Gaji & Tunjangan'); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h4 class="mb-1">Master Gaji & Tunjangan</h4><p class="text-muted mb-0">Gaji pokok, uang makan, transport, jabatan, dan batas bonus KPI per pegawai.</p></div><form class="d-flex gap-2"><input class="form-control" name="q" value="<?php echo e(request('q')); ?>" placeholder="Cari NIK/nama"><button class="btn btn-primary">Cari</button></form></div>
<div class="card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Pegawai</th><th>Cost Center</th><th>Gaji Pokok</th><th>Uang Makan</th><th>Transport</th><th>Tunjangan Jabatan</th><th>Maks. KPI</th><th></th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $employee): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($employee->name); ?></strong><div class="small text-muted"><?php echo e($employee->employee_no); ?></div></td><td><?php echo e($employee->branch?->name ?: 'PT OSM'); ?><div class="small"><?php echo e($employee->position?->name ?: '-'); ?></div></td><td>Rp <?php echo e(number_format((float)$employee->basic_salary,0,',','.')); ?></td><td>Rp <?php echo e(number_format((float)$employee->meal_allowance,0,',','.')); ?></td><td>Rp <?php echo e(number_format((float)$employee->transport_allowance,0,',','.')); ?></td><td>Rp <?php echo e(number_format((float)$employee->position_allowance,0,',','.')); ?></td><td>Rp <?php echo e(number_format((float)$employee->kpi_incentive_max,0,',','.')); ?></td><td><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('employees.update')): ?><a class="btn btn-sm btn-label-primary" href="<?php echo e(route('employees.edit',$employee)); ?>">Edit</a><?php endif; ?></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="8" class="text-center py-5 text-muted">Belum ada pegawai.</td></tr><?php endif; ?>
</tbody></table></div><?php if($employees->hasPages()): ?><div class="card-body"><?php echo e($employees->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.contentNavbarLayout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\laragon\www\appoems\resources\views/hr/compensation/index.blade.php ENDPATH**/ ?>