<?php ($editing = isset($position) && $position->exists); ?>
<div class="row g-3">
  <div class="col-md-2"><label class="form-label">Kode</label><input class="form-control" name="code" required maxlength="50" value="<?php echo e(old('code', $position->code ?? '')); ?>"></div>
  <div class="col-md-4"><label class="form-label">Nama Jabatan</label><input class="form-control" name="name" required value="<?php echo e(old('name', $position->name ?? '')); ?>"></div>
  <div class="col-md-3"><label class="form-label">Divisi</label><select class="form-select" name="division_id"><option value="">Lintas divisi</option><?php $__currentLoopData = $divisions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $division): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($division->id); ?>" <?php if((string) old('division_id', $position->division_id ?? '') === (string) $division->id): echo 'selected'; endif; ?>><?php echo e($division->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
  <div class="col-md-3"><label class="form-label">Atasan Jabatan</label><select class="form-select" name="parent_id"><option value="">Tidak ada</option><?php $__currentLoopData = $parents; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $parent): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(!$editing || $parent->id !== $position->id): ?><option value="<?php echo e($parent->id); ?>" <?php if((string) old('parent_id', $position->parent_id ?? '') === (string) $parent->id): echo 'selected'; endif; ?>><?php echo e($parent->name); ?></option><?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
  <div class="col-md-2"><label class="form-label">Level</label><input class="form-control" type="number" min="1" max="99" name="level" value="<?php echo e(old('level', $position->level ?? 1)); ?>" required></div>
  <div class="col-md-2"><label class="form-label">Grade</label><input class="form-control" name="grade" value="<?php echo e(old('grade', $position->grade ?? '')); ?>"></div>
  <div class="col-md-2"><label class="form-label">Tipe</label><select class="form-select" name="type"><option value="">-</option><?php $__currentLoopData = ['staff','leader','supervisor','manager','director','owner']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($type); ?>" <?php if(old('type', $position->type ?? '') === $type): echo 'selected'; endif; ?>><?php echo e(ucfirst($type)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
  <div class="col-md-2"><label class="form-label">Urutan</label><input class="form-control" type="number" min="0" name="sort_order" value="<?php echo e(old('sort_order', $position->sort_order ?? 0)); ?>"></div>
  <div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active" <?php if(old('status', $position->status ?? 'active') === 'active'): echo 'selected'; endif; ?>>Aktif</option><option value="inactive" <?php if(old('status', $position->status ?? '') === 'inactive'): echo 'selected'; endif; ?>>Nonaktif</option></select></div>
  <div class="col-md-4"><label class="form-label">Default Gaji Pokok</label><input class="form-control" type="number" min="0" name="default_basic_salary" value="<?php echo e(old('default_basic_salary', $position->default_basic_salary ?? 0)); ?>"></div>
  <div class="col-md-4"><label class="form-label">Default Tunjangan</label><input class="form-control" type="number" min="0" name="default_allowance" value="<?php echo e(old('default_allowance', $position->default_allowance ?? 0)); ?>"></div>
  <div class="col-md-4"><label class="form-label">Maks. Bonus KPI</label><input class="form-control" type="number" min="0" name="default_kpi_incentive_max" value="<?php echo e(old('default_kpi_incentive_max', $position->default_kpi_incentive_max ?? 0)); ?>"></div>
  <div class="col-12 d-flex flex-wrap gap-3">
    <?php $__currentLoopData = ['is_management'=>'Manajemen lintas field','is_approver'=>'Dapat menyetujui','is_field_worker'=>'Petugas lapangan','is_kpi_enabled'=>'KPI aktif','is_payroll_enabled'=>'Payroll aktif']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $field=>$label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
      <div class="form-check"><input class="form-check-input" type="checkbox" name="<?php echo e($field); ?>" value="1" id="<?php echo e($field); ?>-<?php echo e($editing ? $position->id : 'new'); ?>" <?php if(old($field, $position->{$field} ?? in_array($field,['is_kpi_enabled','is_payroll_enabled']))): echo 'checked'; endif; ?>><label class="form-check-label" for="<?php echo e($field); ?>-<?php echo e($editing ? $position->id : 'new'); ?>"><?php echo e($label); ?></label></div>
    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
  </div>
</div>
<?php /**PATH C:\laragon\www\appoems\resources\views/master/positions/_form.blade.php ENDPATH**/ ?>