<?php $__env->startSection('title', 'Master Jabatan'); ?>
<?php $__env->startSection('content'); ?>
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h4 class="mb-1">Master Jabatan</h4><p class="text-muted mb-0">Level, hak approval, default gaji, dan batas bonus KPI per jabatan.</p></div></div>
<?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?>
<?php if($errors->any()): ?><div class="alert alert-danger"><ul class="mb-0"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
<?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('position.create')): ?>
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Tambah Jabatan</h5></div><div class="card-body"><form method="POST" action="<?php echo e(route('master.positions.store')); ?>"><?php echo csrf_field(); ?> <?php echo $__env->make('master.positions._form', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><button class="btn btn-primary mt-3"><i class="ri ri-add-line me-1"></i>Simpan Jabatan</button></form></div></div>
<?php endif; ?>
<div class="card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Jabatan</th><th>Divisi/Level</th><th>Default Kompensasi</th><th>Hak</th><th>Status</th><th></th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $positions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $position): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<tr><td><strong><?php echo e($position->name); ?></strong><div class="small text-muted"><?php echo e($position->code); ?> · <?php echo e($position->grade ?: '-'); ?></div></td><td><?php echo e($position->division?->name ?: 'Lintas divisi'); ?><div class="small">Level <?php echo e($position->level); ?> · <?php echo e($position->type ?: '-'); ?></div></td><td>Gaji Rp <?php echo e(number_format((float)$position->default_basic_salary,0,',','.')); ?><div class="small">KPI maks. Rp <?php echo e(number_format((float)$position->default_kpi_incentive_max,0,',','.')); ?></div></td><td><?php if($position->is_management): ?><span class="badge bg-label-info">Management</span><?php endif; ?> <?php if($position->is_approver): ?><span class="badge bg-label-primary">Approver</span><?php endif; ?></td><td><span class="badge bg-label-<?php echo e($position->status === 'active' ? 'success' : 'secondary'); ?>"><?php echo e(ucfirst($position->status)); ?></span></td><td><div class="d-flex gap-1"><?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('position.update')): ?><button class="btn btn-sm btn-label-warning" data-bs-toggle="collapse" data-bs-target="#edit-position-<?php echo e($position->id); ?>">Edit</button><?php endif; ?> <?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('position.delete')): ?><form method="POST" action="<?php echo e(route('master.positions.destroy',$position)); ?>" onsubmit="return confirm('Hapus jabatan ini?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-label-danger">Hapus</button></form><?php endif; ?></div></td></tr>
<?php if (app(\Illuminate\Contracts\Auth\Access\Gate::class)->check('position.update')): ?><tr class="collapse" id="edit-position-<?php echo e($position->id); ?>"><td colspan="6" class="bg-lighter"><form method="POST" action="<?php echo e(route('master.positions.update',$position)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?> <?php echo $__env->make('master.positions._form',['position'=>$position], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><button class="btn btn-warning mt-3">Simpan Perubahan</button></form></td></tr><?php endif; ?>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-5 text-muted">Belum ada jabatan.</td></tr><?php endif; ?>
</tbody></table></div><?php if($positions->hasPages()): ?><div class="card-body"><?php echo e($positions->links()); ?></div><?php endif; ?></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.contentNavbarLayout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\laragon\www\appoems\resources\views/master/positions/index.blade.php ENDPATH**/ ?>