@extends('layouts.contentNavbarLayout')
@section('title', 'Payroll & Biaya Karyawan')
@section('content')
@php($money = fn ($amount) => 'Rp '.number_format((float) $amount, 0, ',', '.'))
<div class="container-fluid">
  <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h4 class="mb-1"><i class="ri ri-funds-line me-2"></i>Payroll & Biaya Karyawan</h4><p class="text-muted mb-0">Pusat laporan biaya PT OSM per company, branch/site, dan pegawai. Bukan semua item langsung merupakan beban kas.</p></div><div class="d-flex gap-2"><a class="btn btn-primary" href="{{ route('hr.payroll.index') }}"><i class="ri ri-money-dollar-circle-line me-1"></i>Kelola Payroll</a><a class="btn btn-label-primary" href="{{ route('hr.operations.index') }}"><i class="ri ri-road-map-line me-1"></i>Dinas & Motor</a></div></div>
  <div class="alert alert-info"><strong>Kontrol akuntansi:</strong> kasbon/piutang dan uang muka dinas dipantau sebagai saldo terbuka, bukan beban riil. Beban dinas menggunakan nominal settlement; motor menggunakan aktual bila sudah tersedia, selain itu hanya rencana.</div>
  <div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Beban payroll terbit</small><h5 class="mb-0">{{ $money($summary['payroll_company_burden']) }}</h5><small>Gaji + beban perusahaan</small></div></div></div><div class="col-sm-6 col-xl-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Take Home Pay terbit</small><h5 class="mb-0">{{ $money($summary['payroll_take_home_pay']) }}</h5><small>Nilai bersih pegawai</small></div></div></div><div class="col-sm-6 col-xl-3"><div class="card h-100 border-warning"><div class="card-body"><small class="text-muted">Piutang / kasbon terbuka</small><h5 class="mb-0">{{ $money($summary['receivable_outstanding']) }}</h5><small>Aset, bukan beban</small></div></div></div><div class="col-sm-6 col-xl-3"><div class="card h-100 border-info"><div class="card-body"><small class="text-muted">Reimbursement disetujui</small><h5 class="mb-0">{{ $money($summary['reimbursement_payable']) }}</h5><small>Menunggu pembayaran finance</small></div></div></div></div>
  <div class="row g-3 mb-4"><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Dinas settled (aktual)</small><h6>{{ $money($summary['trip_actual']) }}</h6></div></div></div><div class="col-md-3"><div class="card h-100 border-warning"><div class="card-body"><small class="text-muted">Uang muka dinas terbuka</small><h6>{{ $money($summary['trip_advance_open']) }}</h6></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Motor aktual</small><h6>{{ $money($summary['vehicle_actual']) }}</h6></div></div></div><div class="col-md-3"><div class="card h-100 border-secondary"><div class="card-body"><small class="text-muted">Rencana motor</small><h6>{{ $money($summary['vehicle_planned']) }}</h6></div></div></div></div>
  <ul class="nav nav-tabs mb-3" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#cost-payroll" type="button">Payroll</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#cost-request" type="button">Kasbon & Reimbursement</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#cost-trip" type="button">Dinas</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#cost-vehicle" type="button">Motor</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#cost-appbill" type="button">AppBill</button></li></ul>
  <div class="tab-content">
    <div class="tab-pane fade show active" id="cost-payroll"><div class="card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Periode</th><th>Slip</th><th>Beban Perusahaan</th><th>THP</th><th>Bonus KPI</th><th>Status</th><th></th></tr></thead><tbody>@forelse($payrollPeriods as $period)<tr><td>{{ sprintf('%02d/%04d', $period->period_month, $period->period_year) }}</td><td>{{ $period->slips_count }}</td><td>{{ $money($period->total_company_burden) }}</td><td>{{ $money($period->total_net) }}</td><td>{{ $money($period->total_kpi_bonus) }}</td><td><span class="badge bg-label-{{ $period->status === 'published' ? 'success' : 'warning' }}">{{ ucfirst($period->status) }}</span></td><td><a class="btn btn-sm btn-label-primary" href="{{ route('hr.payroll.show', $period) }}">Detail</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada payroll.</td></tr>@endforelse</tbody></table></div><div class="card-body">{{ $payrollPeriods->links() }}</div></div></div>
    <div class="tab-pane fade" id="cost-request"><div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-header"><h6 class="mb-0">Pengajuan finansial</h6></div><div class="table-responsive"><table class="table"><thead><tr><th>Pegawai</th><th>Jenis</th><th>Nominal disetujui</th><th>Status</th></tr></thead><tbody>@forelse($requests as $request)<tr><td>{{ $request->employee?->name ?: '-' }}</td><td>{{ str($request->type)->replace('_',' ')->title() }}</td><td>{{ $money($request->approved_amount) }}</td><td>{{ ucfirst($request->status) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Belum ada pengajuan finansial.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-5"><div class="card"><div class="card-header"><h6 class="mb-0">Saldo piutang aktif</h6></div><div class="table-responsive"><table class="table"><thead><tr><th>Pegawai</th><th>No.</th><th>Sisa</th></tr></thead><tbody>@forelse($receivables as $item)<tr><td>{{ $item->employee?->name ?: '-' }}</td><td>{{ $item->receivable_no }}</td><td>{{ $money($item->remaining_amount) }}</td></tr>@empty<tr><td colspan="3" class="text-center text-muted py-4">Tidak ada saldo aktif.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
    <div class="tab-pane fade" id="cost-trip"><div class="card"><div class="table-responsive"><table class="table"><thead><tr><th>No. / Pegawai</th><th>Tujuan</th><th>Uang Muka</th><th>Aktual</th><th>Status</th></tr></thead><tbody>@forelse($trips as $trip)<tr><td>{{ $trip->trip_no }}<div class="small text-muted">{{ $trip->employee?->name }}</div></td><td>{{ $trip->destination }}</td><td>{{ $money($trip->advance_amount) }}</td><td>{{ $trip->actual_amount === null ? '-' : $money($trip->actual_amount) }}</td><td>{{ str($trip->status)->replace('_',' ')->title() }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada data dinas.</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="tab-pane fade" id="cost-vehicle"><div class="card"><div class="table-responsive"><table class="table"><thead><tr><th>Motor</th><th>Jenis</th><th>Rencana</th><th>Aktual</th><th>Jadwal</th><th>Status</th></tr></thead><tbody>@forelse($vehicleExpenses as $expense)<tr><td>{{ $expense->vehicle?->code ?: '-' }}</td><td>{{ str($expense->type)->title() }}</td><td>{{ $money($expense->planned_amount) }}</td><td>{{ $expense->actual_amount === null ? '-' : $money($expense->actual_amount) }}</td><td>{{ $expense->planned_payment_date?->format('d/m/Y') }}</td><td>{{ ucfirst($expense->status) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada biaya motor.</td></tr>@endforelse</tbody></table></div></div></div>
    <div class="tab-pane fade" id="cost-appbill"><div class="card"><div class="card-header"><h6 class="mb-1">Status sinkronisasi AppBill</h6><small class="text-muted">Saat ini event otomatis yang tersedia adalah payroll terbit. Kategori lain ditampilkan di pusat ini sebagai laporan dan menunggu kontrak endpoint AppBill per kategori.</small></div><div class="table-responsive"><table class="table"><thead><tr><th>Event</th><th>Status</th><th>Waktu</th><th>Pesan</th></tr></thead><tbody>@forelse($appBillEvents as $event)<tr><td>{{ $event->event_type }}</td><td>{{ strtoupper($event->status) }}</td><td>{{ $event->created_at?->format('d/m/Y H:i') }}</td><td>{{ data_get($event->response_summary,'code',$event->last_error ?: '-') }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Belum ada event payroll ke AppBill.</td></tr>@endforelse</tbody></table></div></div></div>
  </div>
</div>
@endsection
