@extends('layouts.contentNavbarLayout')
@section('title', 'Detail Payroll')
@section('content')
<div class="container-fluid"><div class="d-flex flex-wrap justify-content-between gap-2 mb-4"><div><a href="{{ route('hr.payroll.index') }}">← Payroll</a><h4 class="mt-2 mb-1">Periode {{ sprintf('%02d/%04d',$period->period_month,$period->period_year) }}</h4><p class="text-muted mb-0">Cost center mengikuti branch/site/product, pemberi kerja tetap PT OSM.</p></div><div class="d-flex gap-2 align-items-start">
@if($period->status === 'draft')<form method="POST" action="{{ route('hr.payroll.approve',$period) }}">@csrf<button class="btn btn-success">Approve HR</button></form>@endif
@if($period->status === 'approved')<form method="POST" action="{{ route('hr.payroll.publish',$period) }}">@csrf<button class="btn btn-primary">Terbitkan ke OvallHR</button></form>@endif
</div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row mb-4"><div class="col-md-3 mb-2"><div class="card"><div class="card-body"><small>Total Bruto</small><h5>Rp {{ number_format((float)$period->total_gross,0,',','.') }}</h5></div></div></div><div class="col-md-3 mb-2"><div class="card"><div class="card-body"><small>Potongan</small><h5>Rp {{ number_format((float)$period->total_deduction,0,',','.') }}</h5></div></div></div><div class="col-md-3 mb-2"><div class="card"><div class="card-body"><small>Neto</small><h5>Rp {{ number_format((float)$period->total_net,0,',','.') }}</h5></div></div></div><div class="col-md-3 mb-2"><div class="card"><div class="card-body"><small>Bonus KPI</small><h5>Rp {{ number_format((float)$period->total_kpi_bonus,0,',','.') }}</h5></div></div></div></div>
<div class="card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Karyawan / cost center</th><th>Bruto</th><th>Piutang</th><th>Neto</th><th>Bonus KPI</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($slips as $slip)<tr><td><strong>{{ $slip->employee_name_snapshot }}</strong><div class="small text-muted">{{ $slip->employee_no_snapshot }} · {{ $slip->branch_name_snapshot ?: '-' }}</div></td><td>Rp {{ number_format((float)$slip->gross_income,0,',','.') }}</td><td>Rp {{ number_format((float)$slip->receivable_deduction,0,',','.') }}</td><td><strong>Rp {{ number_format((float)$slip->net_pay,0,',','.') }}</strong></td><td>Rp {{ number_format((float)$slip->kpi_bonus,0,',','.') }}</td><td>{{ ucfirst($slip->status) }}</td><td><a target="_blank" class="btn btn-sm btn-label-primary" href="{{ route('hr.payroll.payslip',$slip) }}">Cetak</a></td></tr>@empty<tr><td colspan="7" class="text-center py-5 text-muted">Belum ada slip. Pastikan karyawan aktif memiliki gaji pokok.</td></tr>@endforelse
</tbody></table></div><div class="card-body">{{ $slips->links() }}</div></div></div>
@endsection
