@extends('layouts.contentNavbarLayout')
@section('title', 'Rincian Payroll')
@section('content')
@php
 $money=fn($v)=>'Rp '.number_format((float)$v,0,',','.');
 $monthName=\Carbon\Carbon::create($period->period_year,$period->period_month,1)->translatedFormat('F Y');
@endphp
<div class="container-fluid">
 <div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><a href="{{ route('hr.payroll.index',['year'=>$period->period_year]) }}">&larr; Histori Payroll</a><h4 class="mt-2 mb-1">Payroll {{ $monthName }}</h4><p class="text-muted mb-0">Klik nama pegawai untuk melihat seluruh pendapatan, potongan, bank, pembayaran, dan slip.</p></div><div class="d-flex flex-wrap gap-2 align-items-start">
   <a class="btn btn-label-primary" href="{{ route('hr.payroll.export',$period) }}"><i class="ri ri-download-line me-1"></i>Ekspor CSV</a>
   @if($period->status==='draft')<form method="POST" action="{{ route('hr.payroll.approve',$period) }}">@csrf<button class="btn btn-success">Setujui Payroll</button></form>@endif
   @if($period->status==='approved')<form method="POST" action="{{ route('hr.payroll.publish',$period) }}">@csrf<button class="btn btn-primary">Terbitkan Slip OvallHR</button></form>@endif
 </div></div>
 @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
 <div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><small>Total Pendapatan</small><h5>{{ $money($period->total_gross) }}</h5></div></div></div><div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><small>Total Potongan</small><h5>{{ $money($period->total_deduction) }}</h5></div></div></div><div class="col-6 col-xl-3"><div class="card h-100"><div class="card-body"><small>Take Home Pay</small><h5>{{ $money($period->total_net) }}</h5></div></div></div><div class="col-6 col-xl-3"><div class="card h-100 border-success"><div class="card-body"><small>Sudah / Belum Bayar</small><h5 class="text-success">{{ $paidCount }} / <span class="text-warning">{{ $unpaidCount }}</span></h5></div></div></div></div>
 <div class="card mb-3"><div class="card-body"><form method="GET" class="row g-2"><div class="col-md-6"><input class="form-control" name="search" value="{{ $search }}" placeholder="Cari nama, NIK, atau nomor slip"></div><div class="col-md-3"><select class="form-select" name="payment"><option value="all">Semua pembayaran</option><option value="unpaid" @selected($payment==='unpaid')>Belum dibayar</option><option value="paid" @selected($payment==='paid')>Sudah dibayar</option></select></div><div class="col-md-3 d-grid"><button class="btn btn-primary">Filter</button></div></form></div></div>
 <div class="accordion" id="payrollEmployees">@forelse($slips as $slip)@php($income=$slip->items->where('category','income');$deduction=$slip->items->where('category','deduction');$employer=$slip->items->where('category','employer_cost'))
  <div class="accordion-item mb-2 border rounded"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#slip{{ $slip->id }}"><span class="d-flex flex-wrap w-100 align-items-center gap-3 pe-3"><span class="flex-grow-1"><strong>{{ $slip->employee_name_snapshot }}</strong><small class="d-block text-muted">{{ $slip->employee_no_snapshot }} · {{ $slip->branch_name_snapshot ?: '-' }} · {{ $slip->bank_name_snapshot ?: 'Bank belum diisi' }}</small></span><span><small>Take Home Pay</small><strong class="d-block">{{ $money($slip->net_pay) }}</strong></span><span class="badge bg-{{ $slip->payment_status==='paid'?'success':'warning' }}">{{ $slip->payment_status==='paid'?'Sudah Bayar':'Belum Bayar' }}</span></span></button></h2>
   <div id="slip{{ $slip->id }}" class="accordion-collapse collapse" data-bs-parent="#payrollEmployees"><div class="accordion-body">
    <div class="alert alert-secondary py-2"><strong>{{ $slip->slip_no }}</strong> · Rekening: {{ $slip->bank_account_snapshot ?: 'belum tersedia' }} @if($slip->paid_at) · Dibayar {{ $slip->paid_at->format('d/m/Y H:i') }} · Ref {{ $slip->payment_reference ?: '-' }} @endif</div>
    <div class="row g-3"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><strong>Pendapatan</strong></div><div class="table-responsive"><table class="table table-sm mb-0">@forelse($income as $item)<tr><td>{{ $item->name }}</td><td class="text-end">{{ $money($item->amount) }}</td></tr>@empty<tr><td class="text-muted">Tidak ada komponen</td></tr>@endforelse<tr class="fw-bold"><td>Total Pendapatan</td><td class="text-end">{{ $money($slip->gross_income) }}</td></tr></table></div></div></div>
     <div class="col-lg-6"><div class="card h-100"><div class="card-header"><strong>Potongan</strong></div><div class="table-responsive"><table class="table table-sm mb-0">@forelse($deduction as $item)<tr><td>{{ $item->name }}</td><td class="text-end">{{ $money($item->amount) }}</td></tr>@empty<tr><td class="text-muted">Tidak ada potongan</td></tr>@endforelse<tr class="fw-bold"><td>Total Potongan</td><td class="text-end">{{ $money($slip->total_deduction) }}</td></tr></table></div></div></div>
    </div>
    <details class="mt-3"><summary class="text-primary">Lihat beban BPJS perusahaan</summary><div class="table-responsive mt-2"><table class="table table-sm">@forelse($employer as $item)<tr><td>{{ $item->name }}</td><td class="text-end">{{ $money($item->amount) }}</td></tr>@empty<tr><td class="text-muted">Tidak ada komponen.</td></tr>@endforelse<tr class="fw-bold"><td>Total Beban Perusahaan</td><td class="text-end">{{ $money($slip->total_company_burden) }}</td></tr></table></div></details>
    <div class="d-flex flex-wrap justify-content-between gap-2 mt-3"><a target="_blank" class="btn btn-label-primary" href="{{ route('hr.payroll.payslip',$slip) }}">Lihat / Cetak Slip</a>
     @can('payroll.approve')@if($slip->payment_status==='paid')<form method="POST" action="{{ route('hr.payroll.undo-payment',$slip) }}" onsubmit="return confirm('Batalkan catatan pembayaran ini?')">@csrf @method('DELETE')<button class="btn btn-label-danger">Batalkan Status Bayar</button></form>@elseif(in_array($slip->status,['approved','published']))<form method="POST" action="{{ route('hr.payroll.mark-paid',$slip) }}" class="d-flex flex-wrap gap-2">@csrf<input class="form-control" style="max-width:180px" name="payment_reference" placeholder="No. transfer"><input class="form-control" style="max-width:190px" type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required><button class="btn btn-success">Tandai Sudah Bayar</button></form>@endif @endcan
    </div>
   </div></div>
  </div>@empty<div class="card"><div class="card-body text-center text-muted py-5">Data pegawai tidak ditemukan.</div></div>@endforelse</div>
 <div class="mt-3">{{ $slips->links() }}</div>
</div>
@endsection
