@extends('layouts.contentNavbarLayout')
@section('title', 'Piket Kebersihan')
@section('content')
@php($days=[1=>'Senin',2=>'Selasa',3=>'Rabu',4=>'Kamis',5=>'Jumat',6=>'Sabtu',7=>'Minggu'])
<div class="card border-0 mb-4" style="background:linear-gradient(120deg,#102b50,#1d5b93);color:#fff"><div class="card-body p-4"><h3 class="text-white mb-2"><i class="ti ti-broom me-2"></i>Piket Kebersihan & Ruang Server</h3><p class="mb-0 opacity-75">Jadwal per divisi, checklist berbobot, tugas OvallHR otomatis, dan status pelaksanaan transparan.</p></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-4"><div class="col-xl-4"><div class="card"><div class="card-header"><h5>Buat Jadwal</h5></div><div class="card-body"><form method="POST" action="{{ route('hr.cleaning-duty.store') }}" class="row g-3">@csrf
<div class="col-12"><label class="form-label">Jenis *</label><select class="form-select" name="duty_type" id="dutyType"><option value="daily_area">Piket kebersihan harian</option><option value="server_room">Piket khusus ruang/server</option></select></div>
<div class="col-12"><label class="form-label">Divisi *</label><select id="dutyDivision" class="form-select" name="division_id" required><option value="">Pilih divisi</option>@foreach($divisions as $division)<option value="{{ $division->id }}">{{ $division->name }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Petugas *</label><select id="dutyEmployees" class="form-select" name="employee_ids[]" multiple size="6" required>@foreach($employees as $employee)<option data-division="{{ $employee->division_id }}" value="{{ $employee->id }}">{{ $employee->name }} - {{ $employee->employee_no }}</option>@endforeach</select><small>Pilih satu atau beberapa pegawai.</small></div>
<div class="col-6"><label class="form-label">Perulangan</label><select class="form-select" name="recurrence" id="recurrence"><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option></select></div>
<div class="col-6" id="weeklyField"><label class="form-label">Hari</label><select class="form-select" name="weekday">@foreach($days as $v=>$l)<option value="{{ $v }}">{{ $l }}</option>@endforeach</select></div>
<div class="col-6 d-none" id="monthlyField"><label class="form-label">Tanggal (1-28)</label><input class="form-control" type="number" min="1" max="28" name="day_of_month" value="1"></div>
<div class="col-12"><label class="form-label">Nama tugas *</label><input class="form-control" name="title" required value="Piket Kebersihan Area"></div>
<div class="col-12"><label class="form-label">Instruksi</label><textarea class="form-control" name="instructions" rows="3"></textarea></div>
<div class="col-6"><label class="form-label">Mulai *</label><input class="form-control" type="date" name="starts_on" required value="{{ now()->toDateString() }}"></div><div class="col-6"><label class="form-label">Selesai</label><input class="form-control" type="date" name="ends_on"></div>
<div class="col-12"><label class="form-label">Checklist & bobot</label><div id="items"><div class="input-group mb-2"><input class="form-control" name="item_names[]" placeholder="Contoh: cek debu rack/server"><input class="form-control" style="max-width:90px" type="number" min="0" max="100" name="item_weights[]" value="0"><span class="input-group-text">%</span></div></div><button type="button" class="btn btn-sm btn-label-secondary" onclick="addItem()">+ Item</button><div class="form-text">Wajib untuk piket server. Total bobot maksimal 100%.</div></div>
<div class="col-12"><button class="btn btn-primary w-100">Simpan Jadwal & Buat Tugas</button></div></form></div></div></div>
<div class="col-xl-8"><div class="card mb-4"><div class="card-header"><h5>Jadwal Aktif</h5></div><div class="table-responsive"><table class="table"><thead><tr><th>Jenis/Jadwal</th><th>Divisi/Petugas</th><th>Tugas & Checklist</th><th>Status/Aksi</th></tr></thead><tbody>@forelse($schedules as $s)<tr><td><strong>{{ $s->duty_type==='server_room'?'Server/NOC':'Harian' }}</strong><br>{{ $s->recurrence==='monthly'?'Tanggal '.$s->day_of_month:'Setiap '.$days[$s->weekday] }}</td><td>{{ $s->division?->name }}<br><strong>{{ $s->employee?->name }}</strong></td><td>{{ $s->title }}@foreach($s->items as $item)<form class="d-flex gap-1 my-1" method="POST" action="{{ route('hr.cleaning-duty.items.update',$item) }}">@csrf @method('PUT')<input class="form-control form-control-sm" name="item_name" value="{{ $item->item_name }}" required><input class="form-control form-control-sm" style="width:70px" type="number" name="weight" min="0" max="100" value="{{ $item->weight }}"><button class="btn btn-sm btn-label-warning">Edit</button></form><form method="POST" action="{{ route('hr.cleaning-duty.items.destroy',$item) }}">@csrf @method('DELETE')<button class="btn btn-link btn-sm text-danger p-0">Hapus item</button></form>@endforeach<form class="d-flex gap-1 mt-2" method="POST" action="{{ route('hr.cleaning-duty.items.store',$s) }}">@csrf<input class="form-control form-control-sm" name="item_name" required placeholder="Tambah item"><input class="form-control form-control-sm" style="width:70px" type="number" name="weight" min="0" max="100" value="0"><button class="btn btn-sm btn-label-primary">+</button></form></td><td><span class="badge bg-label-{{ $s->is_active?'success':'secondary' }}">{{ $s->is_active?'Aktif':'Nonaktif' }}</span><br><form class="d-inline" method="POST" action="{{ route('hr.cleaning-duty.toggle',$s) }}">@csrf<button class="btn btn-sm btn-label-primary mt-1">Ubah status</button></form><form class="d-inline" method="POST" action="{{ route('hr.cleaning-duty.destroy',$s) }}" onsubmit="return confirm('Hapus jadwal?')">@csrf @method('DELETE')<button class="btn btn-sm btn-label-danger mt-1">Hapus</button></form></td></tr>@empty<tr><td colspan="4" class="text-center py-4">Belum ada jadwal.</td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-header"><h5>Pelaksanaan & Verifikasi HR</h5><small>Status ini otomatis terlihat oleh seluruh pengguna OvallHR.</small></div><div class="table-responsive"><table class="table"><thead><tr><th>Tanggal/Petugas</th><th>Tugas</th><th>Status</th><th>Verifikasi</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ $log->duty_date->format('d/m/Y') }}<br><strong>{{ $log->employee?->name }}</strong><br>{{ $log->division?->name }}</td><td>{{ $log->schedule?->title }}<br><small>Nilai: {{ $log->score }}/100</small></td><td><span class="badge bg-label-{{ $log->status==='completed'?'success':($log->status==='missed'?'danger':'warning') }}">{{ strtoupper(str_replace('_',' ',$log->status)) }}</span></td><td>@if($log->status!=='completed')<form method="POST" action="{{ route('hr.cleaning-duty.complete',$log) }}">@csrf @foreach($log->items as $row)<label class="d-block small"><input type="checkbox" name="completed_items[]" value="{{ $row->cleaning_duty_item_id }}"> {{ $row->item?->item_name }} ({{ $row->item?->weight }}%)</label>@endforeach<input class="form-control form-control-sm my-2" name="completion_note" required placeholder="Catatan/bukti hasil"><button class="btn btn-sm btn-success">Verifikasi Selesai</button></form>@else{{ $log->completion_note }}@endif</td></tr>@empty<tr><td colspan="4" class="text-center py-4">Belum ada pelaksanaan.</td></tr>@endforelse</tbody></table></div></div></div></div>
@push('scripts')<script>function filterEmployees(){const d=document.getElementById('dutyDivision').value;for(const o of document.getElementById('dutyEmployees').options){o.hidden=!!d&&o.dataset.division!==d;if(o.hidden)o.selected=false}}function recurrence(){const monthly=document.getElementById('recurrence').value==='monthly';document.getElementById('monthlyField').classList.toggle('d-none',!monthly);document.getElementById('weeklyField').classList.toggle('d-none',monthly)}function addItem(){document.getElementById('items').insertAdjacentHTML('beforeend','<div class="input-group mb-2"><input class="form-control" name="item_names[]" placeholder="Item pemeriksaan"><input class="form-control" style="max-width:90px" type="number" min="0" max="100" name="item_weights[]" value="0"><span class="input-group-text">%</span></div>')}document.getElementById('dutyDivision').addEventListener('change',filterEmployees);document.getElementById('recurrence').addEventListener('change',recurrence);filterEmployees();recurrence();</script>@endpush
@endsection
