@extends('layouts.contentNavbarLayout')
@section('title', 'BPJS Calculation Engine')
@section('content')
@php($preview = session('bpjs_preview'))
@php($money = fn ($value) => 'Rp '.number_format((float) $value, 0, ',', '.'))
@php($percent = fn ($value) => rtrim(rtrim(number_format((float) $value, 2, '.', ''), '0'), '.'))
<div class="container-fluid">
  <div class="card border-primary mb-4"><div class="card-body d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h4 class="mb-1"><i class="ri ri-calculator-line me-2"></i>BPJS Calculation Engine</h4><p class="mb-0 text-muted">Tarif dan batas upah payroll PT OSM. Persentase cukup isi 4, 3.7, atau 1 â€” maksimal 100%.</p></div><span class="badge bg-label-{{ $setting->aktif ? 'success' : 'danger' }} align-self-lg-center">{{ $setting->aktif ? 'KONFIGURASI AKTIF' : 'NONAKTIF' }}</span></div></div>
  @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
  @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
  <div class="card mb-4" id="bpjs-company-summary">
    <div class="card-header d-flex flex-wrap align-items-center justify-content-between gap-2"><div><h5 class="mb-1">Rekap Kepesertaan & Beban BPJS</h5><p class="mb-0 text-muted small">Nominal dihitung dari gaji pokok, tunjangan tetap, checklist BPJS, dan risiko JKK tiap pegawai aktif.</p></div><a class="btn btn-sm btn-label-primary" href="{{ route('hr.bpjs-readiness.index') }}"><i class="ri ri-shield-check-line me-1"></i>Kesiapan Pendaftaran</a></div>
    <div class="card-body">
      <div class="row g-3 mb-4"><div class="col-sm-6 col-xl-3"><div class="border rounded p-3"><div class="small text-muted">Pegawai aktif / payroll siap</div><strong class="fs-4">{{ $companySummary['counts']['employees'] }} / {{ $companySummary['counts']['payroll_ready'] }}</strong></div></div><div class="col-sm-6 col-xl-3"><div class="border rounded p-3"><div class="small text-muted">Terdaftar BPJS Kesehatan</div><strong class="fs-4">{{ $companySummary['counts']['health_active'] }}</strong></div></div><div class="col-sm-6 col-xl-3"><div class="border rounded p-3"><div class="small text-muted">Terdaftar BPJS Ketenagakerjaan</div><strong class="fs-4">{{ $companySummary['counts']['employment_active'] }}</strong></div></div><div class="col-sm-6 col-xl-3"><div class="border rounded p-3 bg-label-primary"><div class="small">Total beban perusahaan</div><strong class="fs-5">{{ $money($companySummary['totals']['total_bpjs_perusahaan']) }}</strong></div></div></div>
      <div class="alert alert-info small mb-3"><i class="ri ri-information-line me-1"></i>Total potongan karyawan: <strong>{{ $money($companySummary['totals']['total_bpjs_karyawan']) }}</strong>. Rekap ini adalah proyeksi periode berjalan; slip yang sudah terbit tetap memakai snapshot saat payroll dibuat.</div>
      <div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Pegawai</th><th>Dasar upah BPJS</th><th>BPJS Kesehatan</th><th>BPJS Ketenagakerjaan</th><th>Risiko JKK</th><th class="text-end">Beban perusahaan</th><th></th></tr></thead><tbody>
      @forelse($companySummary['employees'] as $row) @php($employee = $row['employee']) @php($calculation = $row['calculation']) @php($formId = 'bpjs-employee-'.$employee->id)
        <tr><td><form id="{{ $formId }}" method="POST" action="{{ route('settings.bpjs-calculation.employees.update', $employee) }}">@csrf @method('PUT')</form><div class="fw-semibold">{{ $employee->name }}</div><small class="text-muted">{{ $employee->employee_no }} Â· Gaji {{ $money($employee->basic_salary) }} + Tunj. {{ $money($employee->fixed_allowance) }}</small></td><td>{{ $money($calculation['bpjs_wage_base']) }}</td><td><input form="{{ $formId }}" type="hidden" name="bpjs_kesehatan_active" value="0"><div class="form-check form-switch"><input form="{{ $formId }}" class="form-check-input" type="checkbox" name="bpjs_kesehatan_active" value="1" @checked($employee->is_bpjs_kesehatan_active)><label class="form-check-label small">Daftarkan</label></div></td><td><input form="{{ $formId }}" type="hidden" name="bpjs_ketenagakerjaan_active" value="0"><div class="form-check form-switch"><input form="{{ $formId }}" class="form-check-input" type="checkbox" name="bpjs_ketenagakerjaan_active" value="1" @checked($employee->is_bpjs_ketenagakerjaan_active)><label class="form-check-label small">Daftarkan</label></div></td><td><select form="{{ $formId }}" name="bpjs_jkk_risk_code" class="form-select form-select-sm"><option value="">Default perusahaan</option>@foreach($riskOptions as $code => $label)<option value="{{ $code }}" @selected($employee->bpjs_jkk_risk_code === $code)>{{ $label }}</option>@endforeach</select><input form="{{ $formId }}" type="hidden" name="basic_salary" value="{{ $employee->basic_salary }}"><input form="{{ $formId }}" type="hidden" name="fixed_allowance" value="{{ $employee->fixed_allowance }}"><input form="{{ $formId }}" type="hidden" name="bpjs_effective_date" value="{{ $employee->bpjs_effective_date?->format('Y-m-d') }}"></td><td class="text-end"><strong>{{ $money($calculation['total_bpjs_perusahaan']) }}</strong><div class="small text-muted">Potongan: {{ $money($calculation['total_bpjs_karyawan']) }}</div></td><td><button form="{{ $formId }}" class="btn btn-sm btn-primary">Simpan</button></td></tr>
      @empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada pegawai aktif pada company ini.</td></tr>@endforelse
      </tbody></table></div>
    </div>
  </div>
  <div class="row g-4">
    <div class="col-xl-8"><form method="POST" action="{{ route('settings.bpjs-calculation.update') }}">@csrf @method('PUT')
      <div class="card mb-4"><div class="card-header"><h5 class="mb-1">BPJS Kesehatan</h5><small class="text-muted">Dasar upah = gaji pokok + tunjangan tetap.</small></div><div class="card-body"><div class="row g-3">
        <div class="col-md-4"><label class="form-label">Porsi perusahaan</label><div class="input-group"><input class="form-control" type="number" step="0.01" min="0" max="100" name="bpjs_kesehatan_perusahaan" value="{{ old('bpjs_kesehatan_perusahaan', $percent($setting->bpjs_kesehatan_perusahaan)) }}"><span class="input-group-text">%</span></div></div>
        <div class="col-md-4"><label class="form-label">Potongan karyawan</label><div class="input-group"><input class="form-control" type="number" step="0.01" min="0" max="100" name="bpjs_kesehatan_karyawan" value="{{ old('bpjs_kesehatan_karyawan', $percent($setting->bpjs_kesehatan_karyawan)) }}"><span class="input-group-text">%</span></div></div>
        <div class="col-md-4"><label class="form-label">Batas upah <small class="text-muted">(opsional)</small></label><div class="input-group"><span class="input-group-text">Rp</span><input class="form-control" type="text" inputmode="numeric" data-rupiah="true" name="bpjs_kesehatan_wage_cap" value="{{ old('bpjs_kesehatan_wage_cap', $setting->bpjs_kesehatan_wage_cap) }}" placeholder="Tanpa batas"></div></div>
      </div></div></div>
      <div class="card mb-4"><div class="card-header"><h5 class="mb-1">BPJS Ketenagakerjaan</h5><small class="text-muted">JHT dan JP dipisahkan agar payroll transparan.</small></div><div class="card-body"><div class="row g-3">
        @foreach([['jht_perusahaan','JHT perusahaan'],['jht_karyawan','JHT karyawan'],['jp_perusahaan','JP perusahaan'],['jp_karyawan','JP karyawan']] as [$field,$label])<div class="col-md-3"><label class="form-label">{{ $label }}</label><div class="input-group"><input class="form-control" type="number" step="0.01" min="0" max="100" name="{{ $field }}" value="{{ old($field, $percent($setting->{$field})) }}"><span class="input-group-text">%</span></div></div>@endforeach
        <div class="col-md-6"><label class="form-label">Batas upah JP <small class="text-muted">(opsional)</small></label><div class="input-group"><span class="input-group-text">Rp</span><input class="form-control" type="text" inputmode="numeric" data-rupiah="true" name="batas_upah_jp" value="{{ old('batas_upah_jp', $setting->batas_upah_jp) }}" placeholder="Tanpa batas"></div></div>
        <div class="col-md-3"><label class="form-label">JKM perusahaan</label><div class="input-group"><input class="form-control" type="number" step="0.01" min="0" max="100" name="jkm" value="{{ old('jkm', $percent($setting->jkm)) }}"><span class="input-group-text">%</span></div></div>
        <div class="col-md-3"><label class="form-label">Default risiko JKK</label><select class="form-select" name="default_jkk_risk_code">@foreach($riskOptions as $code => $label)<option value="{{ $code }}" @selected(old('default_jkk_risk_code', $setting->default_jkk_risk_code) === $code)>{{ $label }}</option>@endforeach</select></div>
      </div></div></div>
      <div class="card mb-4"><div class="card-header"><h5 class="mb-1">Tarif Risiko JKK</h5><small class="text-muted">Pilih risiko pegawai pada data BPJS; angka dapat diubah kapan saja sesuai kebijakan/regulasi.</small></div><div class="card-body"><div class="row g-3">@foreach($riskOptions as $code => $label)<div class="col-md-4"><label class="form-label">{{ $label }}</label><div class="input-group"><input class="form-control" type="number" step="0.01" min="0" max="100" name="jkk_{{ $code }}" value="{{ old('jkk_'.$code, $percent($setting->{'jkk_'.$code})) }}"><span class="input-group-text">%</span></div></div>@endforeach</div></div></div>
      <div class="card"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Berlaku mulai</label><input class="form-control" type="date" name="effective_from" value="{{ old('effective_from', $setting->effective_from?->format('Y-m-d')) }}"></div><div class="col-md-8"><label class="form-label">Catatan perubahan</label><input class="form-control" name="notes" value="{{ old('notes', $setting->notes) }}" placeholder="Contoh: verifikasi tarif periode ..."></div><div class="col-12"><input type="hidden" name="aktif" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="aktif" value="1" id="bpjs-active" @checked(old('aktif', $setting->aktif))><label class="form-check-label" for="bpjs-active">Aktifkan konfigurasi ini untuk payroll baru</label></div></div><div class="col-12"><button class="btn btn-primary"><i class="ri ri-save-line me-1"></i>Simpan Konfigurasi BPJS</button></div></div></div></div>
    </form></div>
    <div class="col-xl-4"><div class="card position-sticky" style="top:1rem"><div class="card-header"><h5 class="mb-0">Simulasi cepat</h5></div><div class="card-body"><p class="small text-muted">Nominal otomatis bertitik saat diketik dan tidak dibatasi jumlah digit.</p><form method="POST" action="{{ route('settings.bpjs-calculation.preview') }}">@csrf
      <div class="mb-3"><label class="form-label">Gaji Pokok</label><div class="input-group"><span class="input-group-text">Rp</span><input class="form-control" type="text" inputmode="numeric" data-rupiah="true" name="basic_salary" value="{{ old('basic_salary') }}" placeholder="1.500.000" required></div></div>
      <div class="mb-3"><label class="form-label">Tunjangan Tetap <small class="text-muted">(opsional)</small></label><div class="input-group"><span class="input-group-text">Rp</span><input class="form-control" type="text" inputmode="numeric" data-rupiah="true" name="fixed_allowance" value="{{ old('fixed_allowance', 0) }}" placeholder="500.000"></div></div>
      <div class="form-check mb-2"><input type="hidden" name="bpjs_kesehatan_active" value="0"><input class="form-check-input" type="checkbox" name="bpjs_kesehatan_active" value="1" id="health-active" @checked(old('bpjs_kesehatan_active', true))><label class="form-check-label" for="health-active">BPJS Kesehatan aktif</label></div><div class="form-check mb-3"><input type="hidden" name="bpjs_ketenagakerjaan_active" value="0"><input class="form-check-input" type="checkbox" name="bpjs_ketenagakerjaan_active" value="1" id="tk-active" @checked(old('bpjs_ketenagakerjaan_active', true))><label class="form-check-label" for="tk-active">BPJS Ketenagakerjaan aktif</label></div>
      <div class="mb-3"><label class="form-label">Risiko JKK</label><select class="form-select" name="risk_code">@foreach($riskOptions as $code => $label)<option value="{{ $code }}" @selected(old('risk_code', $setting->default_jkk_risk_code) === $code)>{{ $label }}</option>@endforeach</select></div><button class="btn btn-primary w-100"><i class="ri ri-calculator-line me-1"></i>Hitung Simulasi</button></form>
      @if($preview)<hr><div class="vstack gap-2 small"><div class="d-flex justify-content-between"><span>Dasar upah BPJS</span><strong>{{ $money($preview['bpjs_wage_base']) }}</strong></div><div class="d-flex justify-content-between"><span>BPJS perusahaan</span><strong>{{ $money($preview['total_bpjs_perusahaan']) }}</strong></div><div class="d-flex justify-content-between"><span>Potongan karyawan</span><strong>{{ $money($preview['total_bpjs_karyawan']) }}</strong></div><hr class="my-1"><div class="d-flex justify-content-between"><span>Total beban perusahaan</span><strong>{{ $money($preview['total_company_burden']) }}</strong></div><div class="d-flex justify-content-between text-primary"><span>Take Home Pay</span><strong>{{ $money($preview['take_home_pay']) }}</strong></div></div>@endif
    </div></div></div>
  </div>
</div>
@endsection
