@extends('layouts.contentNavbarLayout')
@section('title', 'BPJS Calculation Engine')
@section('content')
@php($preview = session('bpjs_preview'))
@php($money = fn ($value) => 'Rp '.number_format((float) $value, 0, ',', '.'))
<div class="container-fluid">
  <div class="card border-primary mb-4"><div class="card-body d-flex flex-column flex-lg-row justify-content-between gap-3"><div><h4 class="mb-1"><i class="ri ri-calculator-line me-2"></i>BPJS Calculation Engine</h4><p class="mb-0 text-muted">Satu sumber tarif untuk payroll PT OSM. Semua persentase dan batas upah di bawah dapat diedit tanpa perubahan kode.</p></div><span class="badge bg-label-{{ $setting->aktif ? 'success' : 'danger' }} align-self-lg-center">{{ $setting->aktif ? 'KONFIGURASI AKTIF' : 'NONAKTIF' }}</span></div></div>
  @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
  @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
  <div class="row g-4">
    <div class="col-xl-8"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Master tarif & batas upah</h5></div><div class="card-body"><form method="POST" action="{{ route('settings.bpjs-calculation.update') }}">@csrf @method('PUT')
      <div class="row g-3"><div class="col-12"><h6 class="text-primary mb-0">BPJS Kesehatan</h6></div>
      <div class="col-md-4"><label class="form-label">Perusahaan (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="bpjs_kesehatan_perusahaan" value="{{ old('bpjs_kesehatan_perusahaan', $setting->bpjs_kesehatan_perusahaan) }}"></div><div class="col-md-4"><label class="form-label">Karyawan (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="bpjs_kesehatan_karyawan" value="{{ old('bpjs_kesehatan_karyawan', $setting->bpjs_kesehatan_karyawan) }}"></div><div class="col-md-4"><label class="form-label">Batas upah kesehatan <small class="text-muted">(kosong=tanpa batas)</small></label><input class="form-control" type="number" min="0" name="bpjs_kesehatan_wage_cap" value="{{ old('bpjs_kesehatan_wage_cap', $setting->bpjs_kesehatan_wage_cap) }}"></div>
      <div class="col-12 pt-2"><h6 class="text-primary mb-0">BPJS Ketenagakerjaan — JHT & JP</h6></div>
      <div class="col-md-3"><label class="form-label">JHT perusahaan (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="jht_perusahaan" value="{{ old('jht_perusahaan', $setting->jht_perusahaan) }}"></div><div class="col-md-3"><label class="form-label">JHT karyawan (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="jht_karyawan" value="{{ old('jht_karyawan', $setting->jht_karyawan) }}"></div><div class="col-md-3"><label class="form-label">JP perusahaan (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="jp_perusahaan" value="{{ old('jp_perusahaan', $setting->jp_perusahaan) }}"></div><div class="col-md-3"><label class="form-label">JP karyawan (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="jp_karyawan" value="{{ old('jp_karyawan', $setting->jp_karyawan) }}"></div>
      <div class="col-md-5"><label class="form-label">Batas upah JP</label><input class="form-control" type="number" min="0" name="batas_upah_jp" value="{{ old('batas_upah_jp', $setting->batas_upah_jp) }}"></div><div class="col-md-3"><label class="form-label">JKM (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="jkm" value="{{ old('jkm', $setting->jkm) }}"></div><div class="col-md-4"><label class="form-label">Default risiko JKK</label><select class="form-select" name="default_jkk_risk_code">@foreach($riskOptions as $code => $label)<option value="{{ $code }}" @selected(old('default_jkk_risk_code', $setting->default_jkk_risk_code) === $code)>{{ $label }}</option>@endforeach</select></div>
      <div class="col-12 pt-2"><h6 class="text-primary mb-0">Master Risiko JKK</h6><small class="text-muted">Tarif risiko dipilih per pegawai pada menu BPJS & Kepatuhan; bila belum diisi menggunakan default di atas.</small></div>
      @foreach($riskOptions as $code => $label)<div class="col-md"><label class="form-label">{{ $label }} (%)</label><input class="form-control" type="number" step="0.0001" min="0" name="jkk_{{ $code }}" value="{{ old('jkk_'.$code, $setting->{'jkk_'.$code}) }}"></div>@endforeach
      <div class="col-md-4"><label class="form-label">Berlaku mulai</label><input class="form-control" type="date" name="effective_from" value="{{ old('effective_from', $setting->effective_from?->format('Y-m-d')) }}"></div><div class="col-md-8"><label class="form-label">Catatan perubahan</label><input class="form-control" name="notes" value="{{ old('notes', $setting->notes) }}" placeholder="Contoh: verifikasi regulasi periode ..."></div>
      <div class="col-12"><input type="hidden" name="aktif" value="0"><div class="form-check"><input class="form-check-input" type="checkbox" name="aktif" value="1" id="bpjs-active" @checked(old('aktif', $setting->aktif))><label class="form-check-label" for="bpjs-active">Aktifkan konfigurasi ini untuk payroll baru</label></div></div><div class="col-12"><button class="btn btn-primary"><i class="ri ri-save-line me-1"></i>Simpan Konfigurasi BPJS</button></div>
      </div></form></div></div></div>
    <div class="col-xl-4"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Simulasi cepat</h5></div><div class="card-body"><p class="small text-muted">Masukkan empat data inti. Simulasi tidak menyimpan atau mengubah data pegawai.</p><form method="POST" action="{{ route('settings.bpjs-calculation.preview') }}">@csrf
      <div class="mb-3"><label class="form-label">Gaji Pokok</label><input class="form-control" type="number" min="0" name="basic_salary" value="{{ old('basic_salary') }}" required></div><div class="mb-3"><label class="form-label">Tunjangan Tetap <small class="text-muted">(opsional)</small></label><input class="form-control" type="number" min="0" name="fixed_allowance" value="{{ old('fixed_allowance', 0) }}"></div>
      <div class="form-check mb-2"><input type="hidden" name="bpjs_kesehatan_active" value="0"><input class="form-check-input" type="checkbox" name="bpjs_kesehatan_active" value="1" id="health-active" @checked(old('bpjs_kesehatan_active', true))><label class="form-check-label" for="health-active">BPJS Kesehatan aktif</label></div><div class="form-check mb-3"><input type="hidden" name="bpjs_ketenagakerjaan_active" value="0"><input class="form-check-input" type="checkbox" name="bpjs_ketenagakerjaan_active" value="1" id="tk-active" @checked(old('bpjs_ketenagakerjaan_active', true))><label class="form-check-label" for="tk-active">BPJS Ketenagakerjaan aktif</label></div>
      <div class="mb-3"><label class="form-label">Risiko JKK</label><select class="form-select" name="risk_code">@foreach($riskOptions as $code => $label)<option value="{{ $code }}" @selected(old('risk_code', $setting->default_jkk_risk_code) === $code)>{{ $label }}</option>@endforeach</select></div><button class="btn btn-outline-primary w-100">Hitung Simulasi</button></form>
      @if($preview)<hr><div class="small"><div class="d-flex justify-content-between"><span>Dasar upah BPJS</span><strong>{{ $money($preview['bpjs_wage_base']) }}</strong></div><div class="d-flex justify-content-between"><span>Total BPJS perusahaan</span><strong>{{ $money($preview['total_bpjs_perusahaan']) }}</strong></div><div class="d-flex justify-content-between"><span>Total potongan karyawan</span><strong>{{ $money($preview['total_bpjs_karyawan']) }}</strong></div><hr><div class="d-flex justify-content-between"><span>Total beban perusahaan</span><strong>{{ $money($preview['total_company_burden']) }}</strong></div><div class="d-flex justify-content-between text-primary"><span>Take Home Pay</span><strong>{{ $money($preview['take_home_pay']) }}</strong></div></div>@endif
    </div></div></div>
  </div>
</div>
@endsection
