@extends('layouts.contentNavbarLayout')
@section('title', 'BPJS & Kepatuhan')
@section('content')
@php($checks = $profile->document_checklist ?? [])
<div class="container-fluid">
  <div class="card border-primary mb-4"><div class="card-body d-flex flex-column flex-lg-row gap-3 justify-content-between align-items-lg-center"><div><h4 class="mb-1"><i class="ri ri-shield-check-line me-2"></i>BPJS & Kepatuhan PT OSM</h4><p class="mb-0 text-muted">Pusat kesiapan data perusahaan dan pekerja untuk F1, F1a, dan F2. Pengajuan akhir tetap melalui kanal resmi BPJS.</p></div><a class="btn btn-outline-primary" target="_blank" href="{{ route('hr.bpjs-readiness.print') }}"><i class="ri ri-printer-line me-1"></i>Cetak Paket Kesiapan</a></div></div>

  <div class="row g-4">
    <div class="col-lg-5"><div class="card h-100"><div class="card-header"><h5 class="mb-0">1. Data pendaftaran pemberi kerja</h5></div><div class="card-body"><form method="POST" action="{{ route('hr.bpjs-readiness.profile.update') }}">@csrf @method('PUT')
      <div class="row g-3"><div class="col-12"><label class="form-label">Status kesiapan</label><select class="form-select" name="registration_status">@foreach(['draft'=>'Draft', 'preparing'=>'Sedang disiapkan', 'submitted'=>'Sudah diajukan', 'active'=>'Aktif', 'needs_review'=>'Perlu review'] as $key=>$label)<option value="{{ $key }}" @selected($profile->registration_status === $key)>{{ $label }}</option>@endforeach</select></div>
      <div class="col-md-6"><label class="form-label">NPP BPJS Ketenagakerjaan</label><input class="form-control" name="bpjs_ketenagakerjaan_npp" value="{{ $profile->bpjs_ketenagakerjaan_npp }}"></div><div class="col-md-6"><label class="form-label">No. daftar BPJS Kesehatan</label><input class="form-control" name="bpjs_kesehatan_registration_no" value="{{ $profile->bpjs_kesehatan_registration_no }}"></div>
      <div class="col-md-6"><label class="form-label">PIC HR</label><input class="form-control" name="pic_name" value="{{ $profile->pic_name }}"></div><div class="col-md-6"><label class="form-label">Jabatan PIC</label><input class="form-control" name="pic_position" value="{{ $profile->pic_position }}"></div>
      <div class="col-md-6"><label class="form-label">Email PIC</label><input class="form-control" name="pic_email" value="{{ $profile->pic_email }}"></div><div class="col-md-6"><label class="form-label">No. HP PIC</label><input class="form-control" name="pic_phone" value="{{ $profile->pic_phone }}"></div>
      <div class="col-md-4"><label class="form-label">Target daftar</label><input class="form-control" type="date" name="target_registration_date" value="{{ $profile->target_registration_date?->format('Y-m-d') }}"></div><div class="col-md-4"><label class="form-label">Tanggal ajukan</label><input class="form-control" type="date" name="submitted_at" value="{{ $profile->submitted_at?->format('Y-m-d') }}"></div><div class="col-md-4"><label class="form-label">Tanggal aktif</label><input class="form-control" type="date" name="activated_at" value="{{ $profile->activated_at?->format('Y-m-d') }}"></div>
      <div class="col-12"><label class="form-label">Checklist kesiapan</label>@foreach(['nib_npwp'=>'NIB/izin usaha dan NPWP PT OSM', 'company_identity'=>'Identitas perusahaan dan kontak PIC', 'worker_identity'=>'NIK, KK, dan data pekerja', 'worker_wage'=>'Data upah/dasar iuran terverifikasi', 'f1_f1a_f2'=>'Form resmi F1 / F1a / F2 telah disiapkan'] as $key=>$label)<div class="form-check"><input type="hidden" name="check_{{ $key }}" value="0"><input class="form-check-input" type="checkbox" name="check_{{ $key }}" value="1" @checked($checks[$key] ?? false)><label class="form-check-label">{{ $label }}</label></div>@endforeach</div>
      <div class="col-12"><label class="form-label">Catatan HR</label><textarea class="form-control" rows="3" name="notes">{{ $profile->notes }}</textarea></div><div class="col-12"><button class="btn btn-primary w-100">Simpan Kesiapan BPJS</button></div></div>
    </form></div></div></div>
    <div class="col-lg-7"><div class="card h-100"><div class="card-header"><h5 class="mb-0">2. Data legal PT OSM yang terbaca dari master</h5></div><div class="card-body"><div class="row g-3"><div class="col-md-6"><small class="text-muted">Badan usaha</small><div class="fw-semibold">{{ $company->legal_name ?: $company->name }}</div></div><div class="col-md-6"><small class="text-muted">NIB / Izin usaha</small><div class="fw-semibold">{{ $company->nib ?: 'Belum diisi' }}</div></div><div class="col-md-6"><small class="text-muted">NPWP badan</small><div class="fw-semibold">{{ $company->npwp ?: 'Belum diisi' }}</div></div><div class="col-md-6"><small class="text-muted">Email perusahaan</small><div class="fw-semibold">{{ $company->email ?: 'Belum diisi' }}</div></div><div class="col-12"><small class="text-muted">Alamat</small><div class="fw-semibold">{{ $company->address ?: 'Belum diisi' }}</div></div></div><hr><div class="alert alert-warning mb-0"><strong>Batas sistem:</strong> halaman ini tidak mengirim data ke BPJS dan bukan bukti kepesertaan. Setelah data siap, HR mengisi/mengunggah formulir resmi BPJS melalui kanal resminya.</div></div></div></div>
  </div>

  <div class="card mt-4"><div class="card-header d-flex justify-content-between"><div><h5 class="mb-0">3. Kesiapan pekerja aktif</h5><small class="text-muted">Siap data dasar: {{ $readyEmployees->count() }} dari {{ $employees->count() }} pegawai aktif.</small></div></div><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Pegawai</th><th>Data F1a</th><th>Status BPJS</th><th>Nomor Peserta</th><th class="text-end">Update</th></tr></thead><tbody>@forelse($employees as $employee)
<tr><td><div class="fw-semibold">{{ $employee->name }}</div><small>{{ $employee->employee_no }} · {{ $employee->employment_status }}</small></td><td>@php($ktpReady = $employee->documents->contains(fn($document) => $document->document_type === 'ktp' && $document->status === 'verified')) @php($kkReady = $employee->documents->contains(fn($document) => $document->document_type === 'kk' && $document->status === 'verified')) @if(filled($employee->identity_number) && filled($employee->kk_number) && filled($employee->join_date) && $ktpReady && $kkReady)<span class="badge bg-label-success">Data & dokumen siap</span>@else<span class="badge bg-label-warning">Lengkapi NIK/KK, tgl masuk, KTP & KK</span>@endif</td><td><span class="badge bg-label-{{ $employee->bpjs_registration_status === 'active' ? 'success' : ($employee->bpjs_registration_status === 'needs_review' ? 'danger' : 'warning') }}">{{ str($employee->bpjs_registration_status)->replace('_', ' ')->title() }}</span></td><td><small>Kes: {{ $employee->bpjs_kesehatan_no ?: '-' }}<br>TK: {{ $employee->bpjs_ketenagakerjaan_no ?: '-' }}</small></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="{{ route('employees.documents.index', $employee) }}" title="Dokumen"><i class="ri ri-folder-lock-line"></i></a> <button class="btn btn-sm btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#employee-{{ $employee->id }}">Edit</button></td></tr>
<tr class="collapse" id="employee-{{ $employee->id }}"><td colspan="5"><form method="POST" action="{{ route('hr.bpjs-readiness.employees.update', $employee) }}" class="row g-2 p-2 bg-label-primary">@csrf @method('PUT')<div class="col-md-3"><label class="form-label">Status</label><select class="form-select form-select-sm" name="bpjs_registration_status">@foreach(['pending','ready','submitted','active','needs_review','not_applicable'] as $status)<option value="{{ $status }}" @selected($employee->bpjs_registration_status === $status)>{{ str($status)->replace('_', ' ')->title() }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">No. BPJS Kesehatan</label><input class="form-control form-control-sm" name="bpjs_kesehatan_no" value="{{ $employee->bpjs_kesehatan_no }}"></div><div class="col-md-3"><label class="form-label">No. BPJS Ketenagakerjaan</label><input class="form-control form-control-sm" name="bpjs_ketenagakerjaan_no" value="{{ $employee->bpjs_ketenagakerjaan_no }}"></div><div class="col-md-2"><label class="form-label">Efektif</label><input class="form-control form-control-sm" type="date" name="bpjs_effective_date" value="{{ $employee->bpjs_effective_date?->format('Y-m-d') }}"></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-sm btn-primary w-100">Simpan</button></div><div class="col-md-3"><label class="form-label">Risiko JKK</label><select class="form-select form-select-sm" name="bpjs_jkk_risk_code"><option value="">Ikuti default perusahaan</option>@foreach(\App\Models\BpjsSetting::riskOptions() as $code => $label)<option value="{{ $code }}" @selected($employee->bpjs_jkk_risk_code === $code)>{{ $label }}</option>@endforeach</select></div><div class="col-md-9"><label class="form-label">Catatan / kekurangan data</label><input class="form-control form-control-sm" name="bpjs_notes" value="{{ $employee->bpjs_notes }}" placeholder="Catatan / kekurangan data"></div></form></td></tr>
@empty<tr><td colspan="5" class="text-center text-muted">Belum ada pegawai aktif.</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
