@extends('layouts.contentNavbarLayout')
@section('title', 'Dokumen Pegawai')
@section('content')
<div class="container-fluid">
  <div class="card border-primary mb-4"><div class="card-body d-flex flex-column flex-lg-row justify-content-between gap-3 align-items-lg-center"><div><h4 class="mb-1"><i class="ri ri-shield-keyhole-line me-2"></i>Dokumen Pegawai: {{ $employee->name }}</h4><p class="mb-0 text-muted">Arsip privat untuk administrasi, kontrak, payroll, dan kesiapan BPJS. File tidak disimpan sebagai link publik.</p></div><a class="btn btn-outline-secondary" href="{{ route('employees.show', $employee) }}">Kembali ke Pegawai</a></div></div>
  <div class="row g-4"><div class="col-lg-4"><div class="card"><div class="card-header"><h5 class="mb-0">Unggah Dokumen</h5></div><div class="card-body"><form method="POST" enctype="multipart/form-data" action="{{ route('employees.documents.store', $employee) }}">@csrf
    <div class="mb-3"><label class="form-label">Jenis dokumen</label><select class="form-select @error('document_type') is-invalid @enderror" name="document_type" required>@foreach($types as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select>@error('document_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="mb-3"><label class="form-label">Judul internal <small class="text-muted">(opsional)</small></label><input class="form-control" name="title" placeholder="Contoh: KTP terbaru 2026"></div>
    <div class="mb-3"><label class="form-label">File</label><input class="form-control @error('file') is-invalid @enderror" type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required><div class="form-text">PDF/JPG/PNG/WEBP, maksimum 10 MB.</div>@error('file')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="mb-3"><label class="form-label">Berlaku sampai <small class="text-muted">(SIM/sertifikat)</small></label><input class="form-control" type="date" name="expires_at"></div>
    <div class="mb-3"><label class="form-label">Catatan</label><textarea class="form-control" rows="2" name="notes"></textarea></div>
    <div class="form-check mb-3"><input type="hidden" name="is_required" value="0"><input class="form-check-input" type="checkbox" name="is_required" value="1" checked><label class="form-check-label">Dokumen wajib onboarding</label></div>
    <button class="btn btn-primary w-100"><i class="ri ri-upload-2-line me-1"></i>Unggah Privat</button>
  </form></div></div>
  <div class="card mt-4 bg-label-warning"><div class="card-body small"><strong>Keamanan:</strong> unggah hanya dokumen yang memang diperlukan. Jangan unggah data kesehatan atau dokumen sensitif lain tanpa kebutuhan kerja dan persetujuan yang sesuai.</div></div></div>
  <div class="col-lg-8"><div class="card"><div class="card-header"><h5 class="mb-0">Arsip & Verifikasi</h5></div><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Dokumen</th><th>File</th><th>Status</th><th>Berlaku</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($documents as $document)
    <tr><td><div class="fw-semibold">{{ $document->title }}</div><small class="text-muted">{{ $types[$document->document_type] ?? $document->document_type }} · diunggah {{ $document->created_at->format('d/m/Y H:i') }}</small></td><td><small>{{ $document->original_name }}<br>{{ number_format($document->file_size / 1024, 1) }} KB</small></td><td><span class="badge bg-label-{{ $document->status === 'verified' ? 'success' : ($document->status === 'rejected' || $document->status === 'expired' ? 'danger' : 'warning') }}">{{ str($document->status)->title() }}</span>@if($document->verifier)<br><small class="text-muted">oleh {{ $document->verifier->name }}</small>@endif</td><td>{{ $document->expires_at?->format('d/m/Y') ?: '-' }}</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('employees.documents.download', [$employee, $document]) }}"><i class="ri ri-download-2-line"></i></a><button class="btn btn-sm btn-outline-warning" data-bs-toggle="collapse" data-bs-target="#verify-{{ $document->id }}"><i class="ri ri-shield-check-line"></i></button><form method="POST" class="d-inline" action="{{ route('employees.documents.destroy', [$employee, $document]) }}" onsubmit="return confirm('Hapus file privat ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="ri ri-delete-bin-line"></i></button></form></td></tr>
    <tr class="collapse" id="verify-{{ $document->id }}"><td colspan="5"><form method="POST" action="{{ route('employees.documents.status', [$employee, $document]) }}" class="row g-2 p-2 bg-label-primary">@csrf @method('PUT')<div class="col-md-3"><select class="form-select form-select-sm" name="status">@foreach(['uploaded'=>'Menunggu verifikasi','verified'=>'Terverifikasi','rejected'=>'Ditolak / revisi','expired'=>'Kedaluwarsa'] as $key=>$label)<option value="{{ $key }}" @selected($document->status === $key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-3"><input class="form-control form-control-sm" type="date" name="expires_at" value="{{ $document->expires_at?->format('Y-m-d') }}"></div><div class="col-md-5"><input class="form-control form-control-sm" name="notes" value="{{ $document->notes }}" placeholder="Catatan verifikasi HR"></div><div class="col-md-1"><button class="btn btn-sm btn-primary w-100">Simpan</button></div></form></td></tr>
  @empty<tr><td colspan="5" class="text-center text-muted py-5">Belum ada dokumen. Mulai dari KTP, KK, dan dokumen payroll/BPJS yang diperlukan.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
</div>
@endsection
