@extends('layouts.contentNavbarLayout')
@section('title', 'Laporan Kepatuhan')
@section('content')
@php($money = fn($value) => 'Rp '.number_format((float) $value, 0, ',', '.'))
<div class="container-fluid">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h4 class="mb-1">Laporan Kepatuhan & Payroll</h4><p class="text-muted mb-0">Ringkasan company aktif. Bukan formulir atau pelaporan resmi BPJS/Coretax.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('settings.bpjs-calculation.index') }}">BPJS Engine</a><a class="btn btn-primary" href="{{ route('hr.bpjs-readiness.index') }}">Kesiapan BPJS</a></div></div>
  <div class="row g-3 mb-4"><div class="col-md-6 col-xl-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Pegawai aktif</small><div class="fs-3 fw-semibold">{{ $summary['employees'] }}</div></div></div></div><div class="col-md-6 col-xl-3"><div class="card h-100"><div class="card-body"><small class="text-muted">BPJS Kesehatan aktif</small><div class="fs-3 fw-semibold">{{ $summary['health_active'] }}</div></div></div></div><div class="col-md-6 col-xl-3"><div class="card h-100"><div class="card-body"><small class="text-muted">BPJS Ketenagakerjaan aktif</small><div class="fs-3 fw-semibold">{{ $summary['employment_active'] }}</div></div></div></div><div class="col-md-6 col-xl-3"><div class="card h-100"><div class="card-body"><small class="text-muted">Data Coretax siap</small><div class="fs-3 fw-semibold">{{ $summary['coretax_ready'] }}</div></div></div></div></div>
  <div class="row g-4"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">BPJS dari Payroll Terbit</h5></div><div class="card-body"><p class="text-muted small">{{ $latestPeriod ? 'Periode '.sprintf('%02d/%04d', $latestPeriod->period_month, $latestPeriod->period_year) : 'Belum ada payroll terbit.' }}</p><div class="d-flex justify-content-between border-bottom py-2"><span>Beban perusahaan</span><strong>{{ $money($summary['bpjs_company']) }}</strong></div><div class="d-flex justify-content-between py-2"><span>Potongan karyawan</span><strong>{{ $money($summary['bpjs_employee']) }}</strong></div></div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Kesiapan Coretax</h5></div><div class="card-body"><p class="text-muted">Validasi minimal NIK, NPWP, dan status pajak dilakukan sebelum ekspor/pelaporan resmi.</p><a class="btn btn-outline-primary" href="{{ route('employees.index') }}">Lengkapi Data Pegawai</a></div></div></div></div>
  <div class="card mt-4"><div class="card-header"><h5 class="mb-0">Pegawai yang Perlu Melengkapi Data Pajak</h5></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pegawai</th><th>NIK</th><th>NPWP</th><th>Status Pajak</th><th></th></tr></thead><tbody>@forelse($employeesNeedingData as $employee)<tr><td>{{ $employee->name }}</td><td>{{ $employee->identity_number ?: 'Belum ada' }}</td><td>{{ $employee->npwp ?: 'Belum ada' }}</td><td>{{ $employee->tax_status ?: 'Belum ada' }}</td><td><a class="btn btn-sm btn-label-primary" href="{{ route('employees.edit', $employee) }}">Lengkapi</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Data pajak pegawai aktif sudah lengkap.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
